export type Resource = 'wood'|'food'|'stone'|'gold'|'iron'|'crystal';
export type BuildingId = 'fire'|'hut'|'lumber'|'farm'|'quarry'|'market'|'tavern'|'forge'|'shrine';
export type Job = 'wood'|'food'|'stone'|'gold';
export type Cost = Partial<Record<Resource,number>>;
export type View = 'town'|'heroes'|'explore'|'destiny';
export type HeroId = 'rhea'|'finn'|'luna'|'kael'|'orin'|'ash';
export type Command = 'attack'|'skill'|'guard'|'heal'|'retreat';
export interface Hero {id:HeroId;level:number;xp:number;}
export interface Battle {region:number;hp:number;maxHp:number;enemyHp:number;attack:number;defense:number;round:number;energy:number;history:string[];}
export interface Expedition {region:number;start:number;end:number;bold:boolean;power:number;}
export interface State {version:1;time:number;savedAt:number;speed:1|3;paused:boolean;resources:Record<Resource,number>;buildings:Record<BuildingId,number>;population:number;jobs:Record<Job,number>;heroes:Hero[];party:HeroId[];explored:number[];cleared:number[];expedition:Expedition|null;battle:Battle|null;research:string[];log:{time:number;text:string;kind:string}[];event:number|null;lastEvent:number;gatherAt:number;ending:boolean;}
export const RESOURCE_NAMES:Record<Resource,string>={wood:'木材',food:'口粮',stone:'石料',gold:'金币',iron:'铁锭',crystal:'魔晶'};
export const BUILDINGS:{id:BuildingId;name:string;tag:string;desc:string;cost:Cost;max:number;need?:BuildingId;effect:string}[]=[
 {id:'fire',name:'篝火',tag:'聚落之心',desc:'黑暗不会自行退去。你将第一根木柴投入火中。',cost:{wood:12},max:1,effect:'收留 3 位流民，开启生产与建设'},
 {id:'hut',name:'旅人小屋',tag:'居民',desc:'屋顶可以漏雨，但不该漏掉一个无家可归的人。',cost:{wood:30,stone:10},max:6,need:'fire',effect:'每级增加 4 人口上限'},
 {id:'lumber',name:'林间伐木场',tag:'木材',desc:'斧声在山谷间回响，一座城正在醒来。',cost:{wood:25,stone:8},max:6,need:'fire',effect:'每级使伐木产量增加 45%'},
 {id:'farm',name:'溪畔农田',tag:'口粮',desc:'你教他们轮作。来自旧世界的记忆，终于有了用处。',cost:{wood:25,stone:8},max:6,need:'fire',effect:'每级使口粮产量增加 45%'},
 {id:'quarry',name:'灰岩采石场',tag:'石料',desc:'敲开山壁，取出城墙未来的骨骼。',cost:{wood:35},max:6,need:'fire',effect:'开启采石分工，每级提高产量'},
 {id:'market',name:'边境集市',tag:'金币',desc:'商队沿着烟火而来。铜币第一次在谷中叮当作响。',cost:{wood:45,stone:20},max:6,need:'fire',effect:'开启贸易分工与资源交易'},
 {id:'tavern',name:'渡鸦酒馆',tag:'冒险者',desc:'一杯麦酒，一纸委托。总有人愿意走入黑暗。',cost:{wood:60,stone:25,gold:20},max:1,need:'fire',effect:'开放冒险者招募与荒野探索'},
 {id:'forge',name:'余火锻造坊',tag:'装备',desc:'铁砧上的每一颗火星，都在为远行的人照路。',cost:{wood:90,stone:60,gold:35},max:6,need:'tavern',effect:'每级全队攻击 +10%、防御 +2'},
 {id:'shrine',name:'无名者圣所',tag:'秘术',desc:'这里不供奉神。这里纪念那些曾经站起来的人。',cost:{stone:110,gold:70,crystal:12},max:6,need:'forge',effect:'开放知识研究，每级全队生命 +8%'}
];
export const HEROES:{id:HeroId;name:string;role:string;initial:string;color:string;quote:string;atk:number;hp:number;def:number;unlock:number;cost:Cost;trait:string}[]=[
 {id:'rhea',name:'蕾娅',role:'流浪剑士',initial:'蕾',color:'copper',quote:'“给我一处可以回来的地方，我替你守住它。”',atk:19,hp:110,def:4,unlock:0,cost:{gold:20},trait:'坚韧 · 全队防御 +2'},
 {id:'finn',name:'芬恩',role:'半精灵游侠',initial:'芬',color:'green',quote:'“森林从不沉默。只是你还没学会倾听。”',atk:24,hp:82,def:2,unlock:0,cost:{gold:30,food:15},trait:'寻路 · 远征速度 +20%'},
 {id:'luna',name:'露娜',role:'失誓修女',initial:'露',color:'blue',quote:'“神没有回应。没关系，我会。”',atk:16,hp:105,def:3,unlock:1,cost:{gold:55},trait:'抚慰 · 战斗治疗提高至 40%'},
 {id:'kael',name:'凯尔',role:'逐星法师',initial:'凯',color:'purple',quote:'“所谓禁忌，不过是神明不愿公开的答案。”',atk:31,hp:78,def:1,unlock:2,cost:{gold:85,crystal:8},trait:'共鸣 · 全队技能伤害 +25%'},
 {id:'orin',name:'奥林',role:'灰誓骑士',initial:'奥',color:'steel',quote:'“我的王国已经覆灭。你们的不会。”',atk:22,hp:150,def:7,unlock:3,cost:{gold:120,iron:15},trait:'壁垒 · 全队防御 +5'},
 {id:'ash',name:'烬',role:'龙裔猎人',initial:'烬',color:'red',quote:'“我的血脉来自龙。我的选择，属于我。”',atk:37,hp:115,def:4,unlock:4,cost:{gold:170,crystal:20},trait:'破鳞 · 对巨龙和神明伤害 +20%'}
];
export const REGIONS=[
 {name:'低语森林',subtitle:'树影之下，第一条路',biome:'迷雾林地',desc:'有人在旧猎人的营地看见绿眼睛。风里传来铁器拖过石面的声响。',boss:'荆棘狼王',epithet:'林中饥饿的阴影',hp:390,atk:28,def:3,power:20,duration:30,cost:6,reward:{wood:65,food:50,gold:35},first:{gold:80,iron:15,crystal:6},story:'狼王倒下后，林间终于传来鸟鸣。你们找到一块旧路标：灰钟修道院，向北三里。'},
 {name:'灰钟废墟',subtitle:'钟声已经沉寂百年',biome:'失落遗迹',desc:'倒塌的穹顶下，亡者仍在举行无人听见的弥撒。一本银扣古书等待着新的读者。',boss:'无面守墓人',epithet:'永夜钟声的守望者',hp:1050,atk:48,def:7,power:65,duration:42,cost:12,reward:{stone:80,gold:55,iron:12,crystal:5},first:{gold:120,iron:25,crystal:15},story:'你合上守墓人的双眼。古书上写着：魔王并非黑暗的源头，只是诸神留在地上的锁。'},
 {name:'赤砂古道',subtitle:'帝国埋在风沙之中',biome:'荒芜边境',desc:'断裂的商路通往黑铁要塞。流亡骑士正在守住最后一座井。',boss:'黑铁督军',epithet:'断旗之下的不死军魂',hp:2100,atk:82,def:12,power:115,duration:55,cost:18,reward:{stone:110,gold:85,iron:24,crystal:9},first:{gold:180,iron:45,crystal:25},story:'黑铁军旗燃尽。骑士摘下头盔，第一次向一个没有王冠的人宣誓。通往魔王之城的道路已经打开。'},
 {name:'永夜王庭',subtitle:'第一誓愿 · 终结魔王',biome:'魔王领地',desc:'王座以无数名字铸成。魔王知道你的来历，也知道你终将来到这里。',boss:'魔王 · 莫尔迦斯',epithet:'万军之主 · 永夜君王',hp:3900,atk:140,def:18,power:165,duration:68,cost:24,reward:{gold:120,iron:32,crystal:20},first:{gold:300,iron:70,crystal:50},story:'魔王的王冠坠落。“我们都不过是棋子。”他最后的声音消失在黎明里。远方的龙脊雪山，亮起了一只金色的眼睛。'},
 {name:'龙脊雪山',subtitle:'第二誓愿 · 屠灭古龙',biome:'极寒龙巢',desc:'山脉的轮廓是一条沉睡的龙。它收藏的不是黄金，而是世间被抹去的历史。',boss:'古龙 · 阿兹拉克',epithet:'焚世者 · 最后的纪元见证者',hp:6500,atk:210,def:24,power:225,duration:82,cost:32,reward:{gold:160,iron:45,crystal:32},first:{gold:500,iron:100,crystal:90},story:'龙翼遮蔽的天空终于敞开。龙心之中藏着一把没有形状的钥匙。你抬起头，看见星空背后的门。'},
 {name:'破碎天穹',subtitle:'最后誓愿 · 凡人弑神',biome:'诸神禁域',desc:'造物主称这里为秩序。你看到的，却是无数世界被剪断的明天。',boss:'秩序之神 · 伊瑟',epithet:'命运的编织者 · 终章',hp:10000,atk:280,def:30,power:300,duration:95,cost:40,reward:{gold:230,iron:60,crystal:50},first:{gold:1000,iron:200,crystal:200},story:'神说，凡人不应拥有选择。你用来自另一个世界的语言回答：不。'}
];
export const RESEARCH=[
 {id:'rotation',name:'异乡农学',desc:'把前世的轮作与堆肥带到这里。所有基础资源产量 +30%。',cost:{gold:70,crystal:12}},
 {id:'steel',name:'淬火之术',desc:'掌握钢铁的温度。全队攻击 +25%。',cost:{gold:110,iron:35,crystal:15}},
 {id:'wards',name:'守护铭文',desc:'将古老符文刻入每一面盾牌。全队防御 +8。',cost:{gold:160,crystal:35}},
 {id:'memory',name:'群星记忆',desc:'想起自己为何而战。全队生命 +30%。',cost:{gold:200,crystal:50}},
 {id:'godslayer',name:'弑神之理',desc:'拆解神术背后的法则。全队攻击 +30%，技能伤害再 +25%。',cost:{gold:350,iron:75,crystal:90}}
] as const;
export const EVENTS=[
 {title:'雨夜的敲门声',text:'三名难民站在镇口。最年幼的孩子怀里，紧紧抱着一袋种子。',choices:[{label:'送去热汤',detail:'花费 10 口粮，获得 25 木材、20 金币',cost:{food:10},reward:{wood:25,gold:20}},{label:'分享营火',detail:'获得 12 口粮',cost:{},reward:{food:12}}]},
 {title:'篝火旁的商人',text:'“在北方，魔晶比金子值钱。”独眼商人悄悄打开一只缠着银线的木匣。',choices:[{label:'换取魔晶',detail:'花费 25 金币，获得 10 魔晶',cost:{gold:25},reward:{crystal:10}},{label:'帮忙卸货',detail:'获得 18 金币',cost:{},reward:{gold:18}}]},
 {title:'旧世界的灵感',text:'看着溪流推动落叶，你突然想起水车的样子。那些平凡的知识，在这里会成为奇迹。',choices:[{label:'制作水车模型',detail:'花费 20 木材，获得 35 口粮、15 铁锭',cost:{wood:20},reward:{food:35,iron:15}},{label:'把想法记下来',detail:'获得 6 魔晶',cost:{},reward:{crystal:6}}]},
 {title:'无名的墓碑',text:'巡林人找到一座被藤蔓覆盖的坟墓。墓碑上没有名字，只刻着：“总有人会抵达明天。”',choices:[{label:'修缮墓地',detail:'花费 15 石料，获得 12 魔晶',cost:{stone:15},reward:{crystal:12}},{label:'献上一束野花',detail:'获得 20 口粮',cost:{},reward:{food:20}}]}
];
export const freshState=(now=Date.now()):State=>({version:1,time:0,savedAt:now,speed:1,paused:false,resources:{wood:20,food:30,stone:15,gold:25,iron:0,crystal:0},buildings:{fire:0,hut:0,lumber:0,farm:0,quarry:0,market:0,tavern:0,forge:0,shrine:0},population:0,jobs:{wood:0,food:0,stone:0,gold:0},heroes:[],party:[],explored:[0,0,0,0,0,0],cleared:[],expedition:null,battle:null,research:[],log:[{time:0,text:'没有系统提示，没有天选之人的王冠。你只有一双手，和一段关于另一个世界的记忆。',kind:'story'},{time:0,text:'风穿过破败的石墙。先收集木材，让火燃起来。',kind:'normal'}],event:null,lastEvent:0,gatherAt:-5,ending:false});
export const clone=(s:State):State=>structuredClone(s);
export const day=(s:State)=>Math.floor(s.time/60)+1;
export const populationCap=(s:State)=>3+s.buildings.hut*4;
export const idleWorkers=(s:State)=>s.population-Object.values(s.jobs).reduce((a,b)=>a+b,0);
export const levelCap=(s:State)=>Math.min(12,3+s.cleared.length*2);
export function costText(cost:Cost){return Object.entries(cost).map(([k,v])=>`${v} ${RESOURCE_NAMES[k as Resource]}`).join(' · ')}
export const canPay=(s:State,cost:Cost)=>Object.entries(cost).every(([k,v])=>s.resources[k as Resource]>=v!);
function pay(s:State,cost:Cost){for(const [k,v] of Object.entries(cost))s.resources[k as Resource]-=v!;}
function grant(s:State,cost:Cost){for(const [k,v] of Object.entries(cost))s.resources[k as Resource]=Math.min(1e9,s.resources[k as Resource]+v!);}
function log(s:State,text:string,kind='normal'){s.log.unshift({time:s.time,text,kind});s.log=s.log.slice(0,100);}
export function buildingCost(s:State,id:BuildingId):Cost{const b=BUILDINGS.find(x=>x.id===id)!;return Object.fromEntries(Object.entries(b.cost).map(([k,v])=>[k,Math.ceil(v!*1.55**s.buildings[id])]));}
export function production(s:State):Record<Job,number>{const boost=s.research.includes('rotation')?1.3:1;return {wood:s.jobs.wood*.65*(1+s.buildings.lumber*.45)*boost,food:s.jobs.food*.65*(1+s.buildings.farm*.45)*boost,stone:s.buildings.quarry?s.jobs.stone*.5*(1+s.buildings.quarry*.4)*boost:0,gold:s.buildings.market?s.jobs.gold*.4*(1+s.buildings.market*.4)*boost:0};}
export function partyStats(s:State){let hp=0,attack=0,defense=0;for(const id of s.party){const h=s.heroes.find(h=>h.id===id);const d=HEROES.find(h=>h.id===id);if(!h||!d)continue;hp+=d.hp+(h.level-1)*22;attack+=d.atk+(h.level-1)*5;defense+=d.def+(h.level-1);}if(s.party.includes('rhea'))defense+=2;if(s.party.includes('orin'))defense+=5;hp*=1+s.buildings.shrine*.08+(s.research.includes('memory')?.3:0);attack*=1+s.buildings.forge*.1+(s.research.includes('steel')?.25:0)+(s.research.includes('godslayer')?.3:0);defense+=s.buildings.forge*2+(s.research.includes('wards')?8:0);return {hp:Math.round(hp),attack:Math.round(attack),defense:Math.round(defense),power:Math.round(attack+hp/15)};}
function awardXP(s:State,amount:number){for(const h of s.heroes){h.xp+=amount;while(h.level<levelCap(s)&&h.xp>=40+h.level*20){h.xp-=40+h.level*20;h.level++;log(s,`${HEROES.find(x=>x.id===h.id)!.name} 升至 ${h.level} 级。`,'good');}h.xp=Math.min(h.xp,40+h.level*20);}}
export function build(s0:State,id:BuildingId):State{const b=BUILDINGS.find(x=>x.id===id);if(!b||s0.buildings[id]>=b.max||(b.need&&!s0.buildings[b.need]))return s0;const cost=buildingCost(s0,id);if(!canPay(s0,cost))return s0;const s=clone(s0);pay(s,cost);s.buildings[id]++;if(id==='fire'){s.population=3;s.jobs.wood=1;s.jobs.food=1;log(s,'火燃起来了。三位流民走出雾气，在火边坐下。你们的城镇，从今晚开始。','story');}else log(s,`${b.name}${s.buildings[id]>1?'升至 '+s.buildings[id]+' 级':'建成'}。${b.effect}。`,'good');return s;}
export function gather(s0:State,resource:Resource):State{if(!['wood','food','stone'].includes(resource)||s0.time-s0.gatherAt<1.5)return s0;const s=clone(s0);grant(s,{[resource]:resource==='stone'?6:8});s.gatherAt=s.time;return s;}
export function hireWorker(s0:State):State{if(!s0.buildings.fire||s0.population>=populationCap(s0)||!canPay(s0,{food:12}))return s0;const s=clone(s0);pay(s,{food:12});s.population++;log(s,'又一位旅人决定留下。多了一双手，也多了一个愿意称这里为家的人。');return s;}
export function assign(s0:State,job:Job,delta:1|-1):State{if(!['wood','food','stone','gold'].includes(job)||![1,-1].includes(delta)||s0.jobs[job]+delta<0||(delta>0&&idleWorkers(s0)<1)||(job==='stone'&&!s0.buildings.quarry)||(job==='gold'&&!s0.buildings.market))return s0;const s=clone(s0);s.jobs[job]+=delta;return s;}
export function recruit(s0:State,id:HeroId):State{const h=HEROES.find(x=>x.id===id);if(!h||!s0.buildings.tavern||s0.cleared.length<h.unlock||s0.heroes.some(x=>x.id===id)||!canPay(s0,h.cost))return s0;const s=clone(s0);pay(s,h.cost);s.heroes.push({id,level:Math.max(1,s.cleared.length),xp:0});if(s.party.length<4&&!s.expedition&&!s.battle)s.party.push(id);log(s,`${h.name} · ${h.role} 加入了余烬镇。${h.quote}`,'story');return s;}
export function toggleParty(s0:State,id:HeroId):State{if(s0.expedition||s0.battle||!s0.heroes.some(x=>x.id===id))return s0;const s=clone(s0);if(s.party.includes(id))s.party=s.party.filter(x=>x!==id);else if(s.party.length<4)s.party.push(id);else return s0;return s;}
export function trainCost(h:Hero):Cost{return {gold:18+h.level*12,food:10+h.level*4};}
export function train(s0:State,id:HeroId):State{const h=s0.heroes.find(x=>x.id===id);if(!h||!s0.buildings.forge||s0.expedition||s0.battle||h.level>=levelCap(s0)||!canPay(s0,trainCost(h)))return s0;const s=clone(s0);pay(s,trainCost(h));s.heroes.find(x=>x.id===id)!.level++;log(s,`${HEROES.find(x=>x.id===id)!.name} 完成训练，升至 ${h.level+1} 级。`,'good');return s;}
export function research(s0:State,id:string):State{const r=RESEARCH.find(x=>x.id===id);if(!r||!s0.buildings.shrine||s0.research.includes(id)||!canPay(s0,r.cost)||s0.battle)return s0;const s=clone(s0);pay(s,r.cost);s.research.push(id);log(s,`领悟「${r.name}」。${r.desc}`,'story');return s;}
export function trade(s0:State,resource:Resource,buy:boolean):State{if(!s0.buildings.market||!['wood','food','stone','iron','crystal'].includes(resource))return s0;const price=resource==='crystal'?35:resource==='iron'?25:12;const cost=buy?{gold:price}:{[resource]:20};if(!canPay(s0,cost))return s0;const s=clone(s0);pay(s,cost);grant(s,buy?{[resource]:20}:{gold:Math.floor(price*.55)});return s;}
export function regionOpen(s:State,i:number){return Number.isInteger(i)&&i>=0&&i<REGIONS.length&&s.buildings.tavern>0&&(i===0||s.cleared.includes(i-1));}
export function expedition(s0:State,region:number,bold=false):State{if(!regionOpen(s0,region)||s0.expedition||s0.battle||!s0.party.length||!canPay(s0,{food:REGIONS[region].cost}))return s0;const s=clone(s0),r=REGIONS[region];pay(s,{food:r.cost});const duration=r.duration*(s.party.includes('finn')?.8:1)*(bold?.8:1);s.expedition={region,start:s.time,end:s.time+duration,bold,power:partyStats(s).power};log(s,`远征队进入${r.name}。${bold?'他们决定深入险境，寻找更丰厚的收获。':'他们沿着旧路谨慎前行。'}`,'explore');return s;}
export function chooseEvent(s0:State,choice:number):State{if(s0.event===null||![0,1].includes(choice))return s0;const e=EVENTS[s0.event],c=e.choices[choice];if(!canPay(s0,c.cost))return s0;const s=clone(s0);pay(s,c.cost);grant(s,c.reward);s.event=null;log(s,`${e.title}：你选择了${c.label}。获得 ${costText(c.reward)}。`,'story');return s;}
export function advance(s0:State,seconds:number):State{if(!Number.isFinite(seconds)||seconds<=0||s0.paused)return s0;const s=clone(s0);seconds=Math.min(seconds,1800);s.time+=seconds;const p=production(s);for(const k of Object.keys(p) as Job[])s.resources[k]=Math.min(1e9,s.resources[k]+p[k]*seconds);if(s.expedition&&s.time>=s.expedition.end){const e=s.expedition,r=REGIONS[e.region],success=e.power>=r.power*(e.bold?1.3:1);const mult=success?(e.bold?1.6:1):.4;const reward=Object.fromEntries(Object.entries(r.reward).map(([k,v])=>[k,Math.ceil(v!*mult)]));grant(s,reward);if(success)s.explored[e.region]++;awardXP(s,success?35+e.region*20:15);log(s,success?`远征队从${r.name}归来，带回 ${costText(reward)}。${s.explored[e.region]===2?'已找到首领的踪迹。':''}`:`远征队在${r.name}遭遇强敌，安全撤回，带回 ${costText(reward)}。提升等级或扩充队伍后再试。`,success?'good':'danger');s.expedition=null;}
 const interval=Math.floor(s.time/150);if(s.buildings.fire&&interval>s.lastEvent&&s.event===null){s.event=(interval-1)%EVENTS.length;s.lastEvent=interval;log(s,`城镇见闻：${EVENTS[s.event].title}。有人在等待你的决定。`,'story');}return s;}
export function startBattle(s0:State,region:number):State{if(!regionOpen(s0,region)||s0.explored[region]<2||s0.cleared.includes(region)||s0.expedition||s0.battle||!s0.party.length)return s0;const s=clone(s0),stats=partyStats(s);s.battle={region,hp:stats.hp,maxHp:stats.hp,enemyHp:REGIONS[region].hp,attack:stats.attack,defense:stats.defense,round:1,energy:3,history:[`${REGIONS[region].boss}挡在你们面前。远征队拔出了武器。`]};log(s,`决战开始：${REGIONS[region].boss}。`,'danger');return s;}
export function intent(b:Battle){const heavy=b.round%3===0;return {heavy,name:heavy?['狂怒扑杀','死亡钟鸣','黑铁冲锋','末日咏唱','焚世龙息','天命裁决'][b.region]:['利爪横扫','墓土侵袭','战斧横斩','暗影之刃','龙爪撕裂','秩序之矛'][b.region],hint:heavy?(b.region===3?'魔王正在咏唱：战技可以打断，坚守也能减伤。':b.region===5?'神罚即将降临：坚守可大幅减伤，本回合治疗会被封印。':'敌人正在蓄力：使用坚守抵御重击。'):'普通攻势：可以进攻积累士气，或把握时机恢复生命。'};}
export function combat(s0:State,command:Command):State{if(!s0.battle||!['attack','skill','guard','heal','retreat'].includes(command))return s0;const source=s0.battle,warning=intent(source);if(command==='skill'&&source.energy<2)return s0;if(command==='heal'&&(!canPay(s0,{food:12})||(source.region===5&&warning.heavy)))return s0;const s=clone(s0),b=s.battle!,r=REGIONS[b.region];if(command==='retreat'){s.battle=null;log(s,`远征队从${r.name}撤退。所有人平安返回，休整后可再次挑战。`,'normal');return s;}
 let damage=0;const notes:string[]=[];if(command==='attack'){damage=Math.max(1,b.attack-r.def);b.energy=Math.min(5,b.energy+1);notes.push('全队协同进攻');}if(command==='skill'){const boost=1.75+(s.party.includes('kael')?.25:0)+(s.research.includes('godslayer')?.25:0);damage=Math.max(1,Math.round(b.attack*boost-r.def));b.energy-=2;notes.push('释放联合战技');}if(command==='guard'){damage=Math.max(1,Math.round(b.attack*.2-r.def));b.energy=Math.min(5,b.energy+1);notes.push('全队架盾坚守，准备反击');}if(command==='heal'){pay(s,{food:12});const hp=Math.min(b.maxHp-b.hp,Math.round(b.maxHp*(s.party.includes('luna')?.4:.27)));b.hp+=hp;notes.push(`使用补给，恢复 ${hp} 生命`);}if(b.region>=4&&s.party.includes('ash'))damage=Math.round(damage*1.2);b.enemyHp=Math.max(0,b.enemyHp-damage);if(damage)notes.push(`造成 ${damage} 伤害`);
 if(b.enemyHp===0){const region=b.region;s.cleared.push(region);grant(s,r.first);awardXP(s,100+region*45);s.battle=null;log(s,`击败${r.boss}！获得 ${costText(r.first)}。`,'good');log(s,r.story,'story');if(region===5){s.ending=true;log(s,'诸神的时代结束了。你没有坐上空缺的神座，而是回到那个最初点起篝火的小镇。人们问今后该信仰什么，你回答：我们自己。','ending');}return s;}
 let incoming=Math.max(1,Math.round(r.atk*(warning.heavy?2.5:1)-b.defense*.65));if(command==='guard')incoming=Math.max(1,Math.round(incoming*.22));if(b.region===3&&warning.heavy&&command==='skill'){incoming=Math.round(incoming*.25);notes.push('末日咏唱被打断');}b.hp=Math.max(0,b.hp-incoming);notes.push(`${warning.name}造成 ${incoming} 伤害`);b.history.unshift(`第 ${b.round} 回合 · ${notes.join('，')}。`);b.history=b.history.slice(0,30);b.round++;if(b.hp===0){s.battle=null;log(s,`远征队未能击败${r.boss}。同伴们互相搀扶着撤回城镇，没有人被留下。训练、锻造或研究后可以重试。`,'danger');}return s;}
export function objective(s:State):{title:string;detail:string;view:View}{if(!s.buildings.fire)return{title:'点亮第一簇篝火',detail:'花费 12 木材生火，收留流民。',view:'town'};if(!s.buildings.hut)return{title:'给流民一个家',detail:'建造旅人小屋，再招收工人并分配生产。',view:'town'};if(!s.buildings.market)return{title:'让商路通向这里',detail:'建造边境集市，分配商人赚取金币。',view:'town'};if(!s.buildings.tavern)return{title:'建成渡鸦酒馆',detail:'冒险者会循着灯火而来。',view:'town'};if(s.heroes.length<2)return{title:'召集你的第一支小队',detail:'雇佣蕾娅与芬恩，开启荒野探索。',view:'heroes'};const i=s.cleared.length;if(i>=6)return{title:'把明天还给人间',detail:'终章已完成。你的城镇与伙伴将继续成长。',view:'destiny'};if(s.explored[i]<2)return{title:`探索${REGIONS[i].name}`,detail:`成功远征 ${s.explored[i]} / 2 次，找到首领的踪迹。`,view:'explore'};return{title:`挑战${REGIONS[i].boss}`,detail:'集结队伍，留意首领预警，完成这一章的决战。',view:'explore'};}
export function decodeSave(raw:string):State{
 if(raw.length>500000)throw Error('存档过大');const s=JSON.parse(raw) as State;const n=(v:unknown,min=0,max=1e9)=>typeof v==='number'&&Number.isFinite(v)&&v>=min&&v<=max;const int=(v:unknown,min=0,max=1e9)=>n(v,min,max)&&Number.isInteger(v);const keys=(obj:unknown,list:string[])=>obj&&typeof obj==='object'&&!Array.isArray(obj)&&Object.keys(obj).length===list.length&&list.every(k=>Object.hasOwn(obj,k));const unique=(a:unknown[])=>new Set(a).size===a.length;const f=freshState();
 if(!s||s.version!==1||!n(s.time)||!n(s.savedAt,0,1e15)||![1,3].includes(s.speed)||typeof s.paused!=='boolean'||!keys(s.resources,Object.keys(f.resources))||!Object.values(s.resources).every(v=>n(v))||!keys(s.buildings,Object.keys(f.buildings))||!BUILDINGS.every(b=>int(s.buildings[b.id],0,b.max))||!int(s.population,0,27)||s.population>populationCap(s)||!keys(s.jobs,Object.keys(f.jobs))||!Object.values(s.jobs).every(v=>int(v,0,27))||idleWorkers(s)<0)throw Error('存档的城镇数据不完整');
 if(!Array.isArray(s.heroes)||s.heroes.length>6||!unique(s.heroes.map(h=>h.id))||s.heroes.some(h=>!HEROES.some(x=>x.id===h.id)||!int(h.level,1,12)||!n(h.xp,0,280))||!Array.isArray(s.party)||s.party.length>4||!unique(s.party)||s.party.some(id=>!s.heroes.some(h=>h.id===id))||!Array.isArray(s.explored)||s.explored.length!==6||!s.explored.every(v=>int(v))||!Array.isArray(s.cleared)||s.cleared.length>6||s.cleared.some((v,i)=>v!==i)||!Array.isArray(s.research)||!unique(s.research)||s.research.some(id=>!RESEARCH.some(r=>r.id===id)))throw Error('存档的冒险数据不完整');
 if(!Array.isArray(s.log)||s.log.length>100||s.log.some(l=>!n(l.time)||typeof l.text!=='string'||l.text.length>3000||typeof l.kind!=='string')||!(s.event===null||int(s.event,0,3))||!int(s.lastEvent)||!n(s.gatherAt,-5)||typeof s.ending!=='boolean')throw Error('存档的手记数据不完整');
 if(s.gatherAt>s.time||s.lastEvent>Math.floor(s.time/150))throw Error('存档的时间记录无效');
 if(s.expedition!==null){const e=s.expedition;if(!e||!int(e.region,0,5)||!regionOpen(s,e.region)||!n(e.start)||!n(e.end)||e.start>s.time||e.end<=e.start||e.end-e.start>100||!n(e.power)||typeof e.bold!=='boolean'||!s.party.length)throw Error('远征记录无效');}
 if(s.battle!==null){const b=s.battle;if(!b||!int(b.region,0,5)||!regionOpen(s,b.region)||s.cleared.includes(b.region)||s.explored[b.region]<2||!s.party.length||s.expedition||!n(b.hp,1)||!n(b.maxHp,1)||b.hp>b.maxHp||!n(b.enemyHp,1,REGIONS[b.region].hp)||!n(b.attack,1)||!n(b.defense)||!int(b.round,1)||!int(b.energy,0,5)||!Array.isArray(b.history)||b.history.length>30||b.history.some(x=>typeof x!=='string'||x.length>1000))throw Error('战斗记录无效');}return s;
}
