/** Fixed encounter data, checked against deterministic personal-turn combat fixtures.
 * One round = every living hero acts once, then the enemy resolves one intent.
 * attack is a per-target pre-defense/pre-resistance value, not total party damage.
 * Armor here is base armor; retain the existing depth-4 boss armor reduction once.
 */
export type Element = 'physical' | 'shadow' | 'fire' | 'radiant';
export type Pattern =
  | 'patrol'
  | 'pack'
  | 'ward'
  | 'bell'
  | 'charge'
  | 'restore'
  | 'curse'
  | 'channel'
  | 'claw'
  | 'flight'
  | 'seal'
  | 'law';
export type EnemyCandidate = {
  region: number;
  node: number;
  name: string;
  hp: number;
  attack: number;
  armor: number;
  element: Element;
  pattern: Pattern;
  heavyMultiplier: number;
  dodge: number;
  targetLevel: number;
  targetTier: number;
  targetUpgrade: number;
};

export const GUARDIANS: readonly EnemyCandidate[] = [
  {
    region: 0,
    node: 1,
    name: '林缘饥狼',
    hp: 3000,
    attack: 250,
    armor: 8,
    element: 'physical',
    pattern: 'patrol',
    heavyMultiplier: 0.65,
    dodge: 0,
    targetLevel: 2,
    targetTier: 1,
    targetUpgrade: 0,
  },
  {
    region: 0,
    node: 2,
    name: '断桥劫掠者',
    hp: 4000,
    attack: 540,
    armor: 15,
    element: 'physical',
    pattern: 'patrol',
    heavyMultiplier: 0.65,
    dodge: 0,
    targetLevel: 3,
    targetTier: 1,
    targetUpgrade: 0,
  },
  {
    region: 0,
    node: 3,
    name: '荆棘獠牙兽',
    hp: 5000,
    attack: 720,
    armor: 22,
    element: 'physical',
    pattern: 'pack',
    heavyMultiplier: 0.7,
    dodge: 0,
    targetLevel: 4,
    targetTier: 1,
    targetUpgrade: 1,
  },
  {
    region: 0,
    node: 4,
    name: '旧塔追猎者',
    hp: 8500,
    attack: 770,
    armor: 30,
    element: 'physical',
    pattern: 'pack',
    heavyMultiplier: 0.75,
    dodge: 0.03,
    targetLevel: 5,
    targetTier: 1,
    targetUpgrade: 2,
  },
  {
    region: 0,
    node: 5,
    name: '狼王近卫',
    hp: 9000,
    attack: 855,
    armor: 40,
    element: 'physical',
    pattern: 'pack',
    heavyMultiplier: 0.8,
    dodge: 0.03,
    targetLevel: 6,
    targetTier: 1,
    targetUpgrade: 3,
  },

  {
    region: 1,
    node: 1,
    name: '墓阶执灯人',
    hp: 3500,
    attack: 3400,
    armor: 12,
    element: 'shadow',
    pattern: 'patrol',
    heavyMultiplier: 0.6,
    dodge: 0,
    targetLevel: 6,
    targetTier: 1,
    targetUpgrade: 2,
  },
  {
    region: 1,
    node: 2,
    name: '失声祷者',
    hp: 4200,
    attack: 4750,
    armor: 20,
    element: 'shadow',
    pattern: 'ward',
    heavyMultiplier: 0.65,
    dodge: 0,
    targetLevel: 8,
    targetTier: 2,
    targetUpgrade: 1,
  },
  {
    region: 1,
    node: 3,
    name: '回廊缚魂者',
    hp: 4500,
    attack: 7440,
    armor: 28,
    element: 'shadow',
    pattern: 'bell',
    heavyMultiplier: 0.7,
    dodge: 0,
    targetLevel: 10,
    targetTier: 2,
    targetUpgrade: 2,
  },
  {
    region: 1,
    node: 4,
    name: '铸钟怨灵',
    hp: 6200,
    attack: 8040,
    armor: 36,
    element: 'shadow',
    pattern: 'ward',
    heavyMultiplier: 0.75,
    dodge: 0.03,
    targetLevel: 12,
    targetTier: 2,
    targetUpgrade: 3,
  },
  {
    region: 1,
    node: 5,
    name: '墓室守誓灵',
    hp: 8200,
    attack: 8685,
    armor: 45,
    element: 'shadow',
    pattern: 'bell',
    heavyMultiplier: 0.8,
    dodge: 0.03,
    targetLevel: 14,
    targetTier: 2,
    targetUpgrade: 3,
  },

  {
    region: 2,
    node: 1,
    name: '沙路收税兵',
    hp: 4500,
    attack: 2300,
    armor: 5,
    element: 'physical',
    pattern: 'patrol',
    heavyMultiplier: 0.65,
    dodge: 0,
    targetLevel: 6,
    targetTier: 1,
    targetUpgrade: 2,
  },
  {
    region: 2,
    node: 2,
    name: '井口黑铁卫',
    hp: 5500,
    attack: 3700,
    armor: 45,
    element: 'physical',
    pattern: 'charge',
    heavyMultiplier: 0.7,
    dodge: 0,
    targetLevel: 8,
    targetTier: 2,
    targetUpgrade: 1,
  },
  {
    region: 2,
    node: 3,
    name: '货站军械长',
    hp: 6500,
    attack: 4100,
    armor: 70,
    element: 'physical',
    pattern: 'charge',
    heavyMultiplier: 0.75,
    dodge: 0,
    targetLevel: 10,
    targetTier: 2,
    targetUpgrade: 2,
  },
  {
    region: 2,
    node: 4,
    name: '黑铁旗官',
    hp: 7800,
    attack: 5000,
    armor: 90,
    element: 'physical',
    pattern: 'restore',
    heavyMultiplier: 0.8,
    dodge: 0,
    targetLevel: 12,
    targetTier: 2,
    targetUpgrade: 3,
  },
  {
    region: 2,
    node: 5,
    name: '军粮护送长',
    hp: 9500,
    attack: 5700,
    armor: 115,
    element: 'physical',
    pattern: 'restore',
    heavyMultiplier: 0.85,
    dodge: 0,
    targetLevel: 14,
    targetTier: 2,
    targetUpgrade: 3,
  },

  {
    region: 3,
    node: 1,
    name: '无名征收官',
    hp: 14500,
    attack: 22000,
    armor: 45,
    element: 'shadow',
    pattern: 'curse',
    heavyMultiplier: 0.7,
    dodge: 0,
    targetLevel: 16,
    targetTier: 3,
    targetUpgrade: 2,
  },
  {
    region: 3,
    node: 2,
    name: '永夜监誓者',
    hp: 17000,
    attack: 24500,
    armor: 55,
    element: 'shadow',
    pattern: 'channel',
    heavyMultiplier: 0.75,
    dodge: 0,
    targetLevel: 18,
    targetTier: 3,
    targetUpgrade: 3,
  },
  {
    region: 3,
    node: 3,
    name: '献名祭司',
    hp: 20000,
    attack: 34100,
    armor: 68,
    element: 'shadow',
    pattern: 'curse',
    heavyMultiplier: 0.8,
    dodge: 0.03,
    targetLevel: 22,
    targetTier: 4,
    targetUpgrade: 3,
  },
  {
    region: 3,
    node: 4,
    name: '王庭黑曜卫',
    hp: 23500,
    attack: 34600,
    armor: 82,
    element: 'shadow',
    pattern: 'channel',
    heavyMultiplier: 0.85,
    dodge: 0,
    targetLevel: 24,
    targetTier: 4,
    targetUpgrade: 4,
  },
  {
    region: 3,
    node: 5,
    name: '王座缄言者',
    hp: 28000,
    attack: 37400,
    armor: 100,
    element: 'shadow',
    pattern: 'channel',
    heavyMultiplier: 0.9,
    dodge: 0.03,
    targetLevel: 26,
    targetTier: 4,
    targetUpgrade: 4,
  },

  {
    region: 4,
    node: 1,
    name: '冻土穴熊',
    hp: 5050,
    attack: 6870,
    armor: 38,
    element: 'physical',
    pattern: 'claw',
    heavyMultiplier: 0.65,
    dodge: 0,
    targetLevel: 12,
    targetTier: 2,
    targetUpgrade: 2,
  },
  {
    region: 4,
    node: 2,
    name: '隘口幼龙',
    hp: 14000,
    attack: 25000,
    armor: 65,
    element: 'fire',
    pattern: 'claw',
    heavyMultiplier: 0.7,
    dodge: 0,
    targetLevel: 18,
    targetTier: 3,
    targetUpgrade: 3,
  },
  {
    region: 4,
    node: 3,
    name: '换鳞守巢龙',
    hp: 17000,
    attack: 38900,
    armor: 85,
    element: 'fire',
    pattern: 'flight',
    heavyMultiplier: 0.8,
    dodge: 0,
    targetLevel: 22,
    targetTier: 4,
    targetUpgrade: 3,
  },
  {
    region: 4,
    node: 4,
    name: '高空巡猎龙',
    hp: 20500,
    attack: 42010,
    armor: 105,
    element: 'fire',
    pattern: 'flight',
    heavyMultiplier: 0.85,
    dodge: 0.03,
    targetLevel: 26,
    targetTier: 4,
    targetUpgrade: 4,
  },
  {
    region: 4,
    node: 5,
    name: '龙心焰卫',
    hp: 24500,
    attack: 45380,
    armor: 130,
    element: 'fire',
    pattern: 'flight',
    heavyMultiplier: 0.9,
    dodge: 0,
    targetLevel: 28,
    targetTier: 4,
    targetUpgrade: 4,
  },

  {
    region: 5,
    node: 1,
    name: '天阶执戟者',
    hp: 30000,
    attack: 50000,
    armor: 95,
    element: 'radiant',
    pattern: 'seal',
    heavyMultiplier: 0.75,
    dodge: 0,
    targetLevel: 28,
    targetTier: 4,
    targetUpgrade: 4,
  },
  {
    region: 5,
    node: 2,
    name: '星桥校准者',
    hp: 33000,
    attack: 53000,
    armor: 115,
    element: 'radiant',
    pattern: 'ward',
    heavyMultiplier: 0.8,
    dodge: 0.03,
    targetLevel: 30,
    targetTier: 5,
    targetUpgrade: 4,
  },
  {
    region: 5,
    node: 3,
    name: '天律抄录官',
    hp: 37000,
    attack: 56000,
    armor: 135,
    element: 'radiant',
    pattern: 'law',
    heavyMultiplier: 0.85,
    dodge: 0,
    targetLevel: 32,
    targetTier: 5,
    targetUpgrade: 5,
  },
  {
    region: 5,
    node: 4,
    name: '命运纺织者',
    hp: 44000,
    attack: 59000,
    armor: 160,
    element: 'radiant',
    pattern: 'law',
    heavyMultiplier: 0.9,
    dodge: 0.03,
    targetLevel: 34,
    targetTier: 6,
    targetUpgrade: 5,
  },
  {
    region: 5,
    node: 5,
    name: '神座裁决使',
    hp: 54000,
    attack: 63000,
    armor: 185,
    element: 'radiant',
    pattern: 'seal',
    heavyMultiplier: 0.95,
    dodge: 0,
    targetLevel: 36,
    targetTier: 6,
    targetUpgrade: 6,
  },
];

export const BOSSES: readonly EnemyCandidate[] = [
  {
    region: 0,
    node: 6,
    name: '荆棘狼王',
    hp: 10000,
    attack: 1500,
    armor: 50,
    element: 'physical',
    pattern: 'pack',
    heavyMultiplier: 0.9,
    dodge: 0,
    targetLevel: 8,
    targetTier: 1,
    targetUpgrade: 3,
  },
  {
    region: 1,
    node: 6,
    name: '无面守墓人',
    hp: 14500,
    attack: 11000,
    armor: 45,
    element: 'shadow',
    pattern: 'bell',
    heavyMultiplier: 0.95,
    dodge: 0,
    targetLevel: 16,
    targetTier: 2,
    targetUpgrade: 5,
  },
  {
    region: 2,
    node: 6,
    name: '黑铁督军',
    hp: 14500,
    attack: 7800,
    armor: 110,
    element: 'physical',
    pattern: 'restore',
    heavyMultiplier: 1,
    dodge: 0,
    targetLevel: 16,
    targetTier: 2,
    targetUpgrade: 5,
  },
  {
    region: 3,
    node: 6,
    name: '魔王·莫尔迦斯',
    hp: 40000,
    attack: 42000,
    armor: 100,
    element: 'shadow',
    pattern: 'channel',
    heavyMultiplier: 1,
    dodge: 0,
    targetLevel: 28,
    targetTier: 4,
    targetUpgrade: 4,
  },
  {
    region: 4,
    node: 6,
    name: '古龙·阿兹拉克',
    hp: 34000,
    attack: 52000,
    armor: 140,
    element: 'fire',
    pattern: 'flight',
    heavyMultiplier: 1.05,
    dodge: 0,
    targetLevel: 30,
    targetTier: 4,
    targetUpgrade: 5,
  },
  {
    region: 5,
    node: 6,
    name: '秩序之神·伊瑟',
    hp: 72000,
    attack: 70000,
    armor: 200,
    element: 'radiant',
    pattern: 'law',
    heavyMultiplier: 1.15,
    dodge: 0,
    targetLevel: 38,
    targetTier: 6,
    targetUpgrade: 6,
  },
];

/** Encounter pattern IDs describe the fixed regional behavior cycles. */
export const PATTERN_CYCLES: Readonly<Record<Pattern, readonly string[]>> = {
  patrol: ['strike', 'strike', 'heavy'],
  pack: ['mark-strike', 'strike', 'heavy'],
  ward: ['ward', 'strike', 'heavy', 'strike'],
  bell: ['ward', 'double-strike', 'heavy', 'strike'],
  charge: ['strike', 'double-strike', 'heavy', 'strike'],
  restore: ['strike', 'heavy', 'restore', 'double-strike'],
  curse: ['curse-strike', 'strike', 'heavy', 'strike'],
  channel: ['strike', 'channel', 'heavy', 'double-strike'],
  claw: ['strike', 'strike', 'heavy', 'strike'],
  flight: ['strike', 'takeoff-strike', 'flying-strike', 'heavy-land'],
  seal: ['seal-strike', 'strike', 'heavy', 'strike'],
  law: ['seal-strike', 'double-strike', 'channel', 'heavy'],
};
