/** Fixed encounter data, checked against the personal-turn engine and public campaigns.
 * One round = every living hero acts once, then the enemy resolves one intent.
 * attack is a per-target pre-defense/pre-resistance value, not total party damage.
 * Armor here is base armor; retain the existing depth-4 boss armor reduction once.
 */
export type Element = 'physical' | 'shadow' | 'fire' | 'radiant';
export type Pattern =
  | 'patrol'
  | 'pack'
  | 'ward'
  | 'bell'
  | 'charge'
  | 'restore'
  | 'curse'
  | 'channel'
  | 'claw'
  | 'flight'
  | 'seal'
  | 'law';
export type EnemyCandidate = {
  region: number;
  node: number;
  name: string;
  hp: number;
  attack: number;
  armor: number;
  element: Element;
  pattern: Pattern;
  heavyMultiplier: number;
  dodge: number;
  targetLevel: number;
  targetTier: number;
  targetUpgrade: number;
};

export const GUARDIANS: readonly EnemyCandidate[] = [
  {
    region: 0,
    node: 1,
    name: '林缘饥狼',
    hp: 300,
    attack: 24,
    armor: 5,
    element: 'physical',
    pattern: 'patrol',
    heavyMultiplier: 0.65,
    dodge: 0,
    targetLevel: 2,
    targetTier: 1,
    targetUpgrade: 0,
  },
  {
    region: 0,
    node: 2,
    name: '断桥劫掠者',
    hp: 500,
    attack: 48,
    armor: 8,
    element: 'physical',
    pattern: 'patrol',
    heavyMultiplier: 0.65,
    dodge: 0,
    targetLevel: 3,
    targetTier: 1,
    targetUpgrade: 0,
  },
  {
    region: 0,
    node: 3,
    name: '荆棘獠牙兽',
    hp: 850,
    attack: 72,
    armor: 10,
    element: 'physical',
    pattern: 'pack',
    heavyMultiplier: 0.7,
    dodge: 0,
    targetLevel: 4,
    targetTier: 1,
    targetUpgrade: 1,
  },
  {
    region: 0,
    node: 4,
    name: '旧塔追猎者',
    hp: 1100,
    attack: 92,
    armor: 14,
    element: 'physical',
    pattern: 'pack',
    heavyMultiplier: 0.75,
    dodge: 0.03,
    targetLevel: 5,
    targetTier: 1,
    targetUpgrade: 2,
  },
  {
    region: 0,
    node: 5,
    name: '狼王近卫',
    hp: 1700,
    attack: 120,
    armor: 18,
    element: 'physical',
    pattern: 'pack',
    heavyMultiplier: 0.8,
    dodge: 0.03,
    targetLevel: 6,
    targetTier: 1,
    targetUpgrade: 2,
  },

  {
    region: 1,
    node: 1,
    name: '墓阶执灯人',
    hp: 1100,
    attack: 95,
    armor: 8,
    element: 'shadow',
    pattern: 'patrol',
    heavyMultiplier: 0.6,
    dodge: 0,
    targetLevel: 6,
    targetTier: 1,
    targetUpgrade: 2,
  },
  {
    region: 1,
    node: 2,
    name: '失声祷者',
    hp: 1900,
    attack: 210,
    armor: 16,
    element: 'shadow',
    pattern: 'ward',
    heavyMultiplier: 0.65,
    dodge: 0,
    targetLevel: 8,
    targetTier: 2,
    targetUpgrade: 1,
  },
  {
    region: 1,
    node: 3,
    name: '回廊缚魂者',
    hp: 2700,
    attack: 280,
    armor: 20,
    element: 'shadow',
    pattern: 'bell',
    heavyMultiplier: 0.7,
    dodge: 0,
    targetLevel: 10,
    targetTier: 2,
    targetUpgrade: 2,
  },
  {
    region: 1,
    node: 4,
    name: '铸钟怨灵',
    hp: 3400,
    attack: 350,
    armor: 25,
    element: 'shadow',
    pattern: 'ward',
    heavyMultiplier: 0.75,
    dodge: 0.03,
    targetLevel: 12,
    targetTier: 2,
    targetUpgrade: 3,
  },
  {
    region: 1,
    node: 5,
    name: '墓室守誓灵',
    hp: 4200,
    attack: 420,
    armor: 30,
    element: 'shadow',
    pattern: 'bell',
    heavyMultiplier: 0.8,
    dodge: 0.03,
    targetLevel: 14,
    targetTier: 2,
    targetUpgrade: 3,
  },

  {
    region: 2,
    node: 1,
    name: '沙路收税兵',
    hp: 1150,
    attack: 100,
    armor: 15,
    element: 'physical',
    pattern: 'patrol',
    heavyMultiplier: 0.65,
    dodge: 0,
    targetLevel: 6,
    targetTier: 1,
    targetUpgrade: 2,
  },
  {
    region: 2,
    node: 2,
    name: '井口黑铁卫',
    hp: 1850,
    attack: 140,
    armor: 35,
    element: 'physical',
    pattern: 'charge',
    heavyMultiplier: 0.7,
    dodge: 0,
    targetLevel: 8,
    targetTier: 2,
    targetUpgrade: 1,
  },
  {
    region: 2,
    node: 3,
    name: '货站军械长',
    hp: 2550,
    attack: 175,
    armor: 50,
    element: 'physical',
    pattern: 'charge',
    heavyMultiplier: 0.75,
    dodge: 0,
    targetLevel: 10,
    targetTier: 2,
    targetUpgrade: 2,
  },
  {
    region: 2,
    node: 4,
    name: '黑铁旗官',
    hp: 3350,
    attack: 220,
    armor: 65,
    element: 'physical',
    pattern: 'restore',
    heavyMultiplier: 0.8,
    dodge: 0,
    targetLevel: 12,
    targetTier: 2,
    targetUpgrade: 3,
  },
  {
    region: 2,
    node: 5,
    name: '军粮护送长',
    hp: 4200,
    attack: 260,
    armor: 80,
    element: 'physical',
    pattern: 'restore',
    heavyMultiplier: 0.85,
    dodge: 0,
    targetLevel: 14,
    targetTier: 2,
    targetUpgrade: 3,
  },

  {
    region: 3,
    node: 1,
    name: '无名征收官',
    hp: 4100,
    attack: 650,
    armor: 30,
    element: 'shadow',
    pattern: 'curse',
    heavyMultiplier: 0.7,
    dodge: 0,
    targetLevel: 16,
    targetTier: 3,
    targetUpgrade: 2,
  },
  {
    region: 3,
    node: 2,
    name: '永夜监誓者',
    hp: 5100,
    attack: 800,
    armor: 36,
    element: 'shadow',
    pattern: 'channel',
    heavyMultiplier: 0.75,
    dodge: 0,
    targetLevel: 18,
    targetTier: 3,
    targetUpgrade: 3,
  },
  {
    region: 3,
    node: 3,
    name: '献名祭司',
    hp: 6800,
    attack: 1100,
    armor: 45,
    element: 'shadow',
    pattern: 'curse',
    heavyMultiplier: 0.8,
    dodge: 0.03,
    targetLevel: 22,
    targetTier: 4,
    targetUpgrade: 3,
  },
  {
    region: 3,
    node: 4,
    name: '王庭黑曜卫',
    hp: 8100,
    attack: 1300,
    armor: 52,
    element: 'shadow',
    pattern: 'channel',
    heavyMultiplier: 0.85,
    dodge: 0,
    targetLevel: 24,
    targetTier: 4,
    targetUpgrade: 4,
  },
  {
    region: 3,
    node: 5,
    name: '王座缄言者',
    hp: 9500,
    attack: 1550,
    armor: 60,
    element: 'shadow',
    pattern: 'channel',
    heavyMultiplier: 0.9,
    dodge: 0.03,
    targetLevel: 26,
    targetTier: 4,
    targetUpgrade: 4,
  },

  {
    region: 4,
    node: 1,
    name: '冻土穴熊',
    hp: 2800,
    attack: 220,
    armor: 25,
    element: 'physical',
    pattern: 'claw',
    heavyMultiplier: 0.65,
    dodge: 0,
    targetLevel: 12,
    targetTier: 2,
    targetUpgrade: 2,
  },
  {
    region: 4,
    node: 2,
    name: '隘口幼龙',
    hp: 4900,
    attack: 700,
    armor: 45,
    element: 'fire',
    pattern: 'claw',
    heavyMultiplier: 0.7,
    dodge: 0,
    targetLevel: 18,
    targetTier: 3,
    targetUpgrade: 3,
  },
  {
    region: 4,
    node: 3,
    name: '换鳞守巢龙',
    hp: 7000,
    attack: 1350,
    armor: 60,
    element: 'fire',
    pattern: 'flight',
    heavyMultiplier: 0.8,
    dodge: 0,
    targetLevel: 22,
    targetTier: 4,
    targetUpgrade: 3,
  },
  {
    region: 4,
    node: 4,
    name: '高空巡猎龙',
    hp: 8500,
    attack: 1700,
    armor: 75,
    element: 'fire',
    pattern: 'flight',
    heavyMultiplier: 0.85,
    dodge: 0.03,
    targetLevel: 26,
    targetTier: 4,
    targetUpgrade: 4,
  },
  {
    region: 4,
    node: 5,
    name: '龙心焰卫',
    hp: 10200,
    attack: 2000,
    armor: 90,
    element: 'fire',
    pattern: 'flight',
    heavyMultiplier: 0.9,
    dodge: 0,
    targetLevel: 28,
    targetTier: 4,
    targetUpgrade: 4,
  },

  {
    region: 5,
    node: 1,
    name: '天阶执戟者',
    hp: 9000,
    attack: 2000,
    armor: 65,
    element: 'radiant',
    pattern: 'seal',
    heavyMultiplier: 0.75,
    dodge: 0,
    targetLevel: 28,
    targetTier: 4,
    targetUpgrade: 4,
  },
  {
    region: 5,
    node: 2,
    name: '星桥校准者',
    hp: 12500,
    attack: 2800,
    armor: 78,
    element: 'radiant',
    pattern: 'ward',
    heavyMultiplier: 0.8,
    dodge: 0.03,
    targetLevel: 30,
    targetTier: 5,
    targetUpgrade: 4,
  },
  {
    region: 5,
    node: 3,
    name: '天律抄录官',
    hp: 15000,
    attack: 3450,
    armor: 90,
    element: 'radiant',
    pattern: 'law',
    heavyMultiplier: 0.85,
    dodge: 0,
    targetLevel: 32,
    targetTier: 5,
    targetUpgrade: 5,
  },
  {
    region: 5,
    node: 4,
    name: '命运纺织者',
    hp: 20000,
    attack: 4050,
    armor: 105,
    element: 'radiant',
    pattern: 'law',
    heavyMultiplier: 0.9,
    dodge: 0.03,
    targetLevel: 34,
    targetTier: 6,
    targetUpgrade: 5,
  },
  {
    region: 5,
    node: 5,
    name: '神座裁决使',
    hp: 24000,
    attack: 4650,
    armor: 115,
    element: 'radiant',
    pattern: 'seal',
    heavyMultiplier: 0.95,
    dodge: 0,
    targetLevel: 36,
    targetTier: 6,
    targetUpgrade: 6,
  },
];

export const BOSSES: readonly EnemyCandidate[] = [
  {
    region: 0,
    node: 6,
    name: '荆棘狼王',
    hp: 3000,
    attack: 150,
    armor: 15,
    element: 'physical',
    pattern: 'pack',
    heavyMultiplier: 0.9,
    dodge: 0,
    targetLevel: 8,
    targetTier: 1,
    targetUpgrade: 2,
  },
  {
    region: 1,
    node: 6,
    name: '无面守墓人',
    hp: 6800,
    attack: 520,
    armor: 30,
    element: 'shadow',
    pattern: 'bell',
    heavyMultiplier: 0.95,
    dodge: 0,
    targetLevel: 16,
    targetTier: 2,
    targetUpgrade: 3,
  },
  {
    region: 2,
    node: 6,
    name: '黑铁督军',
    hp: 7200,
    attack: 380,
    armor: 75,
    element: 'physical',
    pattern: 'restore',
    heavyMultiplier: 1,
    dodge: 0,
    targetLevel: 16,
    targetTier: 2,
    targetUpgrade: 3,
  },
  {
    region: 3,
    node: 6,
    name: '魔王·莫尔迦斯',
    hp: 16500,
    attack: 1750,
    armor: 60,
    element: 'shadow',
    pattern: 'channel',
    heavyMultiplier: 1,
    dodge: 0,
    targetLevel: 28,
    targetTier: 4,
    targetUpgrade: 4,
  },
  {
    region: 4,
    node: 6,
    name: '古龙·阿兹拉克',
    hp: 13000,
    attack: 2400,
    armor: 100,
    element: 'fire',
    pattern: 'flight',
    heavyMultiplier: 1.05,
    dodge: 0,
    targetLevel: 30,
    targetTier: 4,
    targetUpgrade: 5,
  },
  {
    region: 5,
    node: 6,
    name: '秩序之神·伊瑟',
    hp: 30000,
    attack: 5200,
    armor: 125,
    element: 'radiant',
    pattern: 'law',
    heavyMultiplier: 1.15,
    dodge: 0,
    targetLevel: 38,
    targetTier: 6,
    targetUpgrade: 6,
  },
];

/** Intent behavior details are in combat-balance.md; these IDs deliberately
 * describe patterns instead of assuming the new engine's function signatures. */
export const PATTERN_CYCLES: Readonly<Record<Pattern, readonly string[]>> = {
  patrol: ['strike', 'strike', 'heavy'],
  pack: ['mark-strike', 'strike', 'heavy'],
  ward: ['ward', 'strike', 'heavy', 'strike'],
  bell: ['ward', 'double-strike', 'heavy', 'strike'],
  charge: ['strike', 'double-strike', 'heavy', 'strike'],
  restore: ['strike', 'heavy', 'restore', 'double-strike'],
  curse: ['curse-strike', 'strike', 'heavy', 'strike'],
  channel: ['strike', 'channel', 'heavy', 'double-strike'],
  claw: ['strike', 'strike', 'heavy', 'strike'],
  flight: ['strike', 'takeoff-strike', 'flying-strike', 'heavy-land'],
  seal: ['seal-strike', 'strike', 'heavy', 'strike'],
  law: ['seal-strike', 'double-strike', 'channel', 'heavy'],
};
