import type { Resource } from './realm-data.ts';
import type { SiteBillKind, SiteVariant } from './world-types.ts';

export interface SiteDefinition {
  id: string; region: number; depth: 1 | 3; name: string; enemy: string; relicId: string;
  story: string; assault: string; clever: string; origin: string;
  help: 'shatter' | 'interrupt' | 'shield' | 'heal' | 'cleanse' | 'ranged';
  variants: Record<SiteVariant, { name: string; description: string; bill: SiteBillKind; resources: [Resource, Resource] }>;
}
export const SITES: SiteDefinition[] = [
  {id:'S01',region:0,depth:1,name:'弃置猎人工坊',enemy:'锈齿看守机',relicId:'R01',story:'林缘兽道尽头传来空转的齿轮声。腐朽的工坊里，一具机关仍守着最后一张订单；老工匠躲在原料架后等待援手。',assault:'压住守机',clever:'重接传动',origin:'学徒出身',help:'shatter',variants:{A:{name:'齿轮空转',description:'先破除防护，再把重要技能留给卸压窗口。',bill:'construction',resources:['wood','stone']},B:{name:'屋顶积水',description:'开场多一次泄压重击；可备补给组织排水，从侧面取回控制轴。',bill:'supply',resources:['wood','food']}}},
  {id:'S02',region:0,depth:3,name:'荆棘旧营地',enemy:'荆棘追猎兽',relicId:'R02',story:'王国布旗仍挂在旧营地，帐篷间却全是荆棘。中央每天传出同一声求援，那是残响沙漏留下的声音；幸存者正在外围等待撤离。',assault:'截住追猎者',clever:'组织侧道撤离',origin:'边境流民',help:'shield',variants:{A:{name:'巡猎压近',description:'追猎兽会记住伤者，下一轮扑向已点名的目标。',bill:'supply',resources:['food','wood']},B:{name:'荆棘闭合',description:'蓄扑改为群体冲击，随后仍会扑向已点名的伤者。',bill:'construction',resources:['food','stone']}}},
  {id:'S03',region:1,depth:1,name:'沉钟观测台',enemy:'沉钟校时像',relicId:'R03',story:'钟楼已沉入地面，观测台却仍按旧刻度记录星影。大钟每错过一拍，楼梯便重新封闭。分度仪就藏在可进入的钟隙里。',assault:'击停钟卫',clever:'校准钟隙',origin:'学徒出身',help:'interrupt',variants:{A:{name:'刻度完整',description:'结界与恢复轮次分开出现，需要安排破盾和打断。',bill:'sample',resources:['stone','crystal']},B:{name:'钟轴偏移',description:'恢复轮变为群体咏唱；固定偏移轴架可稳定通过。',bill:'construction',resources:['stone','wood']}}},
  {id:'S04',region:1,depth:3,name:'失名藏书室',enemy:'缄言抄录官',relicId:'R04',story:'目录上的人名被刮去了，只有借阅日期留在纸上。你读出一个日期，书架后的东西便回答：尚未归还。共鸣折页束缚在这份旧契约中。',assault:'破除禁借令',clever:'核对借阅契约',origin:'隐修者',help:'heal',variants:{A:{name:'墨迹未干',description:'禁愈结束后，抄录官将追索攻击最高的旅人。',bill:'sample',resources:['crystal','wood']},B:{name:'纸页倒卷',description:'开场先恢复自身；可打断，也可以组织见证者抄录契约。',bill:'supply',resources:['wood','stone']}}},
  {id:'S05',region:2,depth:1,name:'断轨矿场',enemy:'缚轨搬运者',relicId:'R05',story:'满载矿石的车厢悬在断轨末端，拖矿铁偶不断尝试拉回它。铁偶早已忘了矿场停工的原因，运输总闸依旧锁死。',assault:'拆除牵引铁偶',clever:'搭设旁路轨道',origin:'旧王国佣兵',help:'shatter',variants:{A:{name:'满载车列',description:'牵引时重甲，卸载时低甲；把爆发留给窗口。',bill:'construction',resources:['iron','stone']},B:{name:'熔渣堵轨',description:'卸载重击附带灼烧，低甲窗口仍保留。',bill:'sample',resources:['iron','wood']}}},
  {id:'S06',region:2,depth:3,name:'流沙驿站',enemy:'沙鳍巡掠者',relicId:'R06',story:'地图标着一口井，井边却只有半截屋顶。风停时，有人从沙面下敲三下木板。下层遗留的守约绳结仍在等待护送者。',assault:'驱离沙鳍巡掠者',clever:'锚定驿站绳索',origin:'行商护卫',help:'shield',variants:{A:{name:'风路平稳',description:'跃沙时减免近战，可用远程、迫降或等待落点。',bill:'supply',resources:['food','wood']},B:{name:'流沙改道',description:'首次跃沙多停留一轮，之后仍会落地。',bill:'construction',resources:['food','iron']}}},
  {id:'S07',region:3,depth:1,name:'解誓铸坊',enemy:'誓炉铸卫',relicId:'R07',story:'铸炉里没有燃料，炉火却仍在燃烧。墙上誓词每缺一个字，铁门的锁便多一环。只有切断旧军约，才能取出余温接续匣。',assault:'击破誓炉卫',clever:'转移誓炉余温',origin:'学徒出身',help:'cleanse',variants:{A:{name:'炉温稳定',description:'提前打断过载可免灼烧，冷却轮露出低甲。',bill:'sample',resources:['iron','stone']},B:{name:'誓词重燃',description:'开场点燃一名旅人；也可搭隔热支架避开守卫。',bill:'construction',resources:['iron','crystal']}}},
  {id:'S08',region:3,depth:3,name:'夜幕避难所',enemy:'缚门誓影',relicId:'R08',story:'门没有锁，守卫却不让任何人离开。影子重复着：外面危险，留下安全。居民传出字条，希望你解除把保护变成囚禁的旧誓。',assault:'解除庇护誓影',clever:'建立可信撤离线',origin:'边境流民',help:'heal',variants:{A:{name:'人群安静',description:'禁愈后追击伤者，提前安排护盾与行动顺序。',bill:'supply',resources:['food','wood']},B:{name:'警报回响',description:'追击变为可打断群体咏唱，保留反制士气。',bill:'sample',resources:['food','crystal']}}},
  {id:'S09',region:4,depth:1,name:'冻裂猎台',enemy:'霜翼台卫',relicId:'R09',story:'猎台被冰劈成两半，配给柜仍挂在高处。顺风时悬索相撞，逆风时响声变成翅膀声。古猎人的吊索还可以重新架起。',assault:'赶走霜翼台卫',clever:'重架吊索',origin:'山地猎户',help:'ranged',variants:{A:{name:'顺风索道',description:'落台轮有两次破绽，留给重要输出。',bill:'construction',resources:['wood','food']},B:{name:'逆风冰裂',description:'落台前多一次群体冲击，等待窗口时也要自保。',bill:'supply',resources:['wood','iron']}}},
  {id:'S10',region:4,depth:3,name:'龙眠洞窟',enemy:'眠鳞石卫',relicId:'R10',story:'没有成年龙的洞窟，岩壁却随着呼吸般的热浪起伏。猎月钩嵌在石茧上，旁边留下了一份未完成的约定。',assault:'击碎眠鳞石卫',clever:'疏导热脉',origin:'隐修者',help:'cleanse',variants:{A:{name:'热脉平缓',description:'恢复与过载分开出现，不要过早花完反制资源。',bill:'sample',resources:['crystal','stone']},B:{name:'热脉逆流',description:'恢复改为结界，处理办法从双打断转为破盾和打断。',bill:'construction',resources:['iron','crystal']}}},
  {id:'S11',region:5,depth:1,name:'断律观星台',enemy:'断律轨道卫',relicId:'R11',story:'观星盘仍照着早已破碎的星空运行。每偏离一次旧轨道，守卫便抹去一条新记录。真实星位可以使它摆脱失效的神律。',assault:'中止轨道裁定',clever:'重录星轨序列',origin:'学徒出身',help:'interrupt',variants:{A:{name:'轨道可辨',description:'最强攻击者会被点名，结界与咏唱交替。',bill:'sample',resources:['crystal','iron']},B:{name:'残环偏转',description:'点名改为两段命中，护盾要逐次承伤。',bill:'construction',resources:['crystal','stone']}}},
  {id:'S12',region:5,depth:3,name:'众声圣所',enemy:'独声裁决像',relicId:'R12',story:'神像前放着许多无名供物，回声却只承认一种祈祷。被拒绝的声音汇成障壁；普通人的供物清单能让圣所重新容纳众声。',assault:'打破独声裁决',clever:'召集共同见证',origin:'隐修者',help:'heal',variants:{A:{name:'回声分明',description:'禁愈、结界与审判轮流出现，安排完整反制顺序。',bill:'supply',resources:['food','stone']},B:{name:'残响重叠',description:'开场额外群体攻击，之后进入已预告循环。',bill:'sample',resources:['food','crystal']}}},
];
export const siteDefinition = (id: string) => SITES.find(site => site.id === id);
