/** Three-route skill expansion; pure data shared by both game builds.
 * 36 active skills + 36 passive nodes. Existing role.root/a1/a2/b1/b2 are preserved.
 * Points: Lv5/10/15/20/25/30/35/40 = 8; a complete branch costs 8.
 * Slots: root always available; Lv20 unlocks a second carried branch skill.
 */
import type { TreeSkill, TreeRole, SkillModifier } from './skill-tree-data.ts';

export type ExtensionNode = {
  id: string;
  role: TreeRole;
  branch: 'a' | 'b' | 'c';
  depth: 1 | 2 | 3 | 4;
  name: string;
  type: 'active' | 'passive';
  skillId?: string;
  modifiers?: SkillModifier;
  minLevel: 10 | 20 | 25 | 30 | 35 | 40;
  pointCost: 1 | 2 | 3;
  requires: readonly string[];
};

export const V14_ACTIVE_SKILLS = [
  {
    id: 'wayfarer_riposte',
    role: 'rhea',
    name: '游身还击',
    description:
      '造成125%本人攻击伤害；自己在下次敌方阶段闪避率增加10个百分点，仍受40%总上限约束。',
    target: 'self',
    energy: 2,
    cooldown: 3,
    damage: 1.25,
    evasion: 0.1,
  },
  {
    id: 'breach_lunge',
    role: 'rhea',
    name: '摧阵突进',
    description:
      '造成200%本人攻击伤害并击碎当前护盾；本次暴击率增加5个百分点，不打断补给或咏唱。',
    target: 'enemy',
    energy: 3,
    cooldown: 4,
    damage: 2,
    shatter: true,
    critBonus: 0.05,
  },
  {
    id: 'comrades_bastion',
    role: 'rhea',
    name: '同袍壁垒',
    description:
      '每位存活队友获得本轮45%减伤护佑，覆盖本轮所有敌方攻击；同类只取较强效果。',
    target: 'party',
    energy: 4,
    cooldown: 6,
    damage: 0,
    wardHits: 1,
  },
  {
    id: 'unbending_return',
    role: 'rhea',
    name: '百折归刃',
    description:
      '造成145%本人攻击伤害，恢复自身最大生命12%与攻击50%的生命，并嘲讽下次敌方单体攻击。',
    target: 'self',
    energy: 3,
    cooldown: 5,
    damage: 1.45,
    healing: {
      actorHp: 0.12,
      actorAttack: 0.5,
      targetHp: 0,
    },
    taunt: 1,
  },
  {
    id: 'toxin_fletching',
    role: 'finn',
    name: '毒羽箭',
    description:
      '造成80%本人投射伤害，附加3轮毒伤，每轮为本人施放时攻击的25%；持续伤害不暴击。',
    target: 'enemy',
    energy: 2,
    cooldown: 4,
    damage: 0.8,
    projectile: true,
    dot: {
      kind: 'poison',
      actorAttack: 0.25,
      rounds: 3,
    },
  },
  {
    id: 'forest_screen',
    role: 'finn',
    name: '林幕掩护',
    description:
      '造成90%本人投射伤害；每位存活队友在接下来的敌方阶段承伤降低25%，同类减伤取较强效果。',
    target: 'party',
    energy: 3,
    cooldown: 5,
    damage: 0.9,
    projectile: true,
    incomingMultiplier: 0.75,
  },
  {
    id: 'cloudsplit_aim',
    role: 'finn',
    name: '穿云狙击',
    description:
      '造成240%本人投射伤害，本次额外穿甲20个百分点、暴击率增加10个百分点；不打断、不破盾。',
    target: 'enemy',
    energy: 4,
    cooldown: 5,
    damage: 2.4,
    projectile: true,
    pierceBonus: 0.2,
    critBonus: 0.1,
  },
  {
    id: 'thornwind_volley',
    role: 'finn',
    name: '棘风连射',
    description:
      '造成110%本人投射伤害，附加3轮每轮50%攻击的毒伤；随后一次直接伤害提高20%。',
    target: 'enemy',
    energy: 4,
    cooldown: 6,
    damage: 1.1,
    projectile: true,
    dot: {
      kind: 'poison',
      actorAttack: 0.5,
      rounds: 3,
    },
    markHits: 1,
  },
  {
    id: 'penitent_light',
    role: 'luna',
    name: '告解之光',
    description:
      '造成110%本人投射伤害，同时治疗指定友方，回复本人最大生命8%与攻击40%的生命；不消耗药囊。',
    target: 'ally',
    energy: 3,
    cooldown: 4,
    damage: 1.1,
    projectile: true,
    healing: {
      actorHp: 0.08,
      actorAttack: 0.4,
      targetHp: 0,
    },
  },
  {
    id: 'mercy_procession',
    role: 'luna',
    name: '行世恩光',
    description:
      '消耗1药囊，治疗全体存活队友；每人回复本人最大生命12%、攻击65%与该队友最大生命4%的生命，不复活。',
    target: 'party',
    energy: 4,
    cooldown: 6,
    damage: 0,
    supply: 1,
    healing: {
      actorHp: 0.12,
      actorAttack: 0.65,
      targetHp: 0.04,
    },
  },
  {
    id: 'silver_sanctuary',
    role: 'luna',
    name: '银誓圣所',
    description:
      '每位存活队友获得本人最大生命15%与攻击60%的护盾，持续2轮；接下来的敌方阶段承伤再降低25%。',
    target: 'party',
    energy: 4,
    cooldown: 6,
    damage: 0,
    shield: {
      actorHp: 0.15,
      actorAttack: 0.6,
      rounds: 2,
    },
    incomingMultiplier: 0.75,
  },
  {
    id: 'mortal_verdict',
    role: 'luna',
    name: '凡人裁决',
    description:
      '造成190%本人投射伤害并击碎当前护盾；本人获得两次45%减伤护佑，最多持续两次敌方阶段；不打断。',
    target: 'self',
    energy: 4,
    cooldown: 5,
    damage: 1.9,
    projectile: true,
    shatter: true,
    wardHits: 2,
  },
  {
    id: 'aether_siphon',
    role: 'kael',
    name: '以太汲取',
    description:
      '造成105%本人投射伤害；耗2士气后返还1点，净消耗1点。不能反复凭空增加士气。',
    target: 'enemy',
    energy: 2,
    cooldown: 3,
    damage: 1.05,
    projectile: true,
    energyRefund: 1,
  },
  {
    id: 'prism_interdict',
    role: 'kael',
    name: '折光封禁',
    description:
      '造成110%本人投射伤害并打断当前补给或咏唱；全体活人获得本人最大生命10%与攻击50%的护盾，持续2轮。',
    target: 'party',
    energy: 4,
    cooldown: 6,
    damage: 1.1,
    projectile: true,
    interrupt: true,
    shield: {
      actorHp: 0.1,
      actorAttack: 0.5,
      rounds: 2,
    },
  },
  {
    id: 'falling_constellation',
    role: 'kael',
    name: '星群陨落',
    description:
      '造成200%本人投射伤害，附加3轮每轮35%本人攻击的燃烧；持续伤害不暴击，不破盾或打断。',
    target: 'enemy',
    energy: 4,
    cooldown: 6,
    damage: 2,
    projectile: true,
    dot: {
      kind: 'fire',
      actorAttack: 0.35,
      rounds: 3,
    },
  },
  {
    id: 'arcane_unraveling',
    role: 'kael',
    name: '奥术解构',
    description:
      '造成210%本人投射伤害，额外穿甲20个百分点并打断当前补给或咏唱；耗5士气返1，净消耗4点。',
    target: 'enemy',
    energy: 5,
    cooldown: 6,
    damage: 2.1,
    projectile: true,
    pierceBonus: 0.2,
    interrupt: true,
    energyRefund: 1,
  },
  {
    id: 'oath_hammer',
    role: 'orin',
    name: '誓约重击',
    description: '造成145%本人攻击伤害并击碎当前护盾；不打断敌方补给或咏唱。',
    target: 'enemy',
    energy: 3,
    cooldown: 4,
    damage: 1.45,
    shatter: true,
  },
  {
    id: 'rallying_standard',
    role: 'orin',
    name: '聚阵战旗',
    description:
      '造成60%本人攻击伤害；全体活人获得一次45%减伤护佑，标记敌人供随后两次直接伤害增伤20%；耗4士气返1。',
    target: 'party',
    energy: 4,
    cooldown: 6,
    damage: 0.6,
    wardHits: 1,
    markHits: 2,
    energyRefund: 1,
  },
  {
    id: 'iron_vigil',
    role: 'orin',
    name: '铁壁守望',
    description:
      '嘲讽下次单体攻击，自己在接下来的敌方阶段承伤降低80%；获得本人最大生命25%与攻击40%的护盾，持续2轮。',
    target: 'self',
    energy: 3,
    cooldown: 5,
    damage: 0,
    incomingMultiplier: 0.2,
    taunt: 1,
    shield: {
      actorHp: 0.25,
      actorAttack: 0.4,
      rounds: 2,
    },
  },
  {
    id: 'dawn_sentence',
    role: 'orin',
    name: '破晓裁断',
    description:
      '造成200%本人攻击伤害，本次额外穿甲20个百分点；回复自身最大生命8%与攻击30%的生命。',
    target: 'self',
    energy: 4,
    cooldown: 5,
    damage: 2,
    pierceBonus: 0.2,
    healing: {
      actorHp: 0.08,
      actorAttack: 0.3,
      targetHp: 0,
    },
  },
  {
    id: 'venomscale_bolt',
    role: 'ash',
    name: '毒鳞箭',
    description:
      '造成100%本人投射伤害，附加3轮毒伤，每轮为本人施放时攻击的30%；不附加燃烧。',
    target: 'enemy',
    energy: 3,
    cooldown: 4,
    damage: 1,
    projectile: true,
    dot: {
      kind: 'poison',
      actorAttack: 0.3,
      rounds: 3,
    },
  },
  {
    id: 'cleansing_barrage',
    role: 'ash',
    name: '净鳞齐射',
    description:
      '造成100%本人投射伤害；清除所有存活队友灼烧，并防止他们在下次敌方阶段新受灼烧；不治疗、不破盾。',
    target: 'party',
    energy: 4,
    cooldown: 6,
    damage: 1,
    projectile: true,
    cleanseBurn: true,
    preventBurn: true,
  },
  {
    id: 'highpeak_lance',
    role: 'ash',
    name: '绝峰贯矢',
    description:
      '造成220%本人投射伤害并击碎护盾，本次额外穿甲20个百分点；在龙脊雪山与破碎天穹再增伤15%，不打断。',
    target: 'enemy',
    energy: 5,
    cooldown: 6,
    damage: 2.2,
    projectile: true,
    shatter: true,
    pierceBonus: 0.2,
    lateBossMultiplier: 1.15,
  },
  {
    id: 'ancient_fang',
    role: 'ash',
    name: '古血毒牙',
    description:
      '造成160%本人投射伤害，附加3轮每轮50%本人攻击的毒伤；与自己的毒效果刷新，不无限叠层。',
    target: 'enemy',
    energy: 4,
    cooldown: 6,
    damage: 1.6,
    projectile: true,
    dot: {
      kind: 'poison',
      actorAttack: 0.5,
      rounds: 3,
    },
  },
  {
    id: 'dancing_knife',
    role: 'nyx',
    name: '舞刃',
    description:
      '造成110%本人攻击伤害；自己在下次敌方阶段闪避率增加15个百分点，受40%总上限约束。',
    target: 'self',
    energy: 2,
    cooldown: 3,
    damage: 1.1,
    evasion: 0.15,
  },
  {
    id: 'septic_cut',
    role: 'nyx',
    name: '蚀骨切口',
    description:
      '造成100%本人攻击伤害，附加3轮每轮65%本人攻击的毒伤；持续伤害不暴击，不叠无限层。',
    target: 'enemy',
    energy: 4,
    cooldown: 6,
    damage: 1,
    dot: {
      kind: 'poison',
      actorAttack: 0.65,
      rounds: 3,
    },
  },
  {
    id: 'ghost_return',
    role: 'nyx',
    name: '影返',
    description:
      '造成160%本人攻击伤害；自己在下次敌方阶段闪避率增加25个百分点且承伤降低35%，闪避仍受40%上限约束。',
    target: 'self',
    energy: 4,
    cooldown: 5,
    damage: 1.6,
    evasion: 0.25,
    incomingMultiplier: 0.65,
  },
  {
    id: 'last_silhouette',
    role: 'nyx',
    name: '终幕剪影',
    description:
      '造成300%本人攻击伤害，本次暴击率增加20个百分点、穿甲增加10个百分点；高消耗长冷却，不保证暴击。',
    target: 'enemy',
    energy: 5,
    cooldown: 7,
    damage: 3,
    critBonus: 0.2,
    pierceBonus: 0.1,
  },
  {
    id: 'wild_claw',
    role: 'sylva',
    name: '荒野爪击',
    description:
      '造成120%本人攻击伤害，回复自身最大生命7%与攻击20%的生命；不消耗药囊。',
    target: 'self',
    energy: 2,
    cooldown: 3,
    damage: 1.2,
    healing: {
      actorHp: 0.07,
      actorAttack: 0.2,
      targetHp: 0,
    },
  },
  {
    id: 'briar_prison',
    role: 'sylva',
    name: '繁棘牢笼',
    description:
      '造成90%本人投射伤害，附加3轮每轮50%本人攻击的毒伤；标记敌人供随后两次直接伤害增伤20%，不阻止敌方行动。',
    target: 'enemy',
    energy: 4,
    cooldown: 6,
    damage: 0.9,
    projectile: true,
    dot: {
      kind: 'poison',
      actorAttack: 0.5,
      rounds: 3,
    },
    markHits: 2,
  },
  {
    id: 'four_seasons',
    role: 'sylva',
    name: '四时复苏',
    description:
      '全体存活队友获得3次再生，每次回复本人最大生命4%与攻击35%的生命；续期不叠加，不会复活。',
    target: 'party',
    energy: 4,
    cooldown: 6,
    damage: 0,
    regen: {
      actorHp: 0.04,
      actorAttack: 0.35,
      rounds: 3,
    },
  },
  {
    id: 'ancient_sentinel',
    role: 'sylva',
    name: '古木守卫',
    description:
      '造成140%本人攻击伤害并嘲讽下次单体攻击；自己获得20%本人生命与50%攻击的2轮护盾，以及两次3%本人生命与20%攻击的再生。',
    target: 'self',
    energy: 4,
    cooldown: 6,
    damage: 1.4,
    taunt: 1,
    shield: {
      actorHp: 0.2,
      actorAttack: 0.5,
      rounds: 2,
    },
    regen: {
      actorHp: 0.03,
      actorAttack: 0.2,
      rounds: 2,
    },
  },
  {
    id: 'flash_reagent',
    role: 'vera',
    name: '闪爆试剂',
    description:
      '造成80%本人投射伤害并打断当前补给或咏唱；不击碎护盾，不附加持续伤害。',
    target: 'enemy',
    energy: 3,
    cooldown: 4,
    damage: 0.8,
    projectile: true,
    interrupt: true,
  },
  {
    id: 'triage_mist',
    role: 'vera',
    name: '急救药云',
    description:
      '消耗1药囊，净化全体存活队友灼烧；每人回复本人攻击50%与目标最大生命4%的生命，不复活。',
    target: 'party',
    energy: 4,
    cooldown: 6,
    damage: 0,
    supply: 1,
    cleanseBurn: true,
    healing: {
      actorHp: 0,
      actorAttack: 0.5,
      targetHp: 0.04,
    },
  },
  {
    id: 'whitefire_flask',
    role: 'vera',
    name: '白焰裂瓶',
    description:
      '造成140%本人投射伤害，附加3轮每轮65%本人攻击的燃烧；高消耗长冷却，持续伤害不暴击。',
    target: 'enemy',
    energy: 5,
    cooldown: 7,
    damage: 1.4,
    projectile: true,
    dot: {
      kind: 'fire',
      actorAttack: 0.65,
      rounds: 3,
    },
  },
  {
    id: 'dissolving_charge',
    role: 'vera',
    name: '解构爆剂',
    description:
      '造成200%本人投射伤害并击碎护盾，本次额外穿甲25个百分点；不打断补给或咏唱。',
    target: 'enemy',
    energy: 4,
    cooldown: 5,
    damage: 2,
    projectile: true,
    shatter: true,
    pierceBonus: 0.25,
  },
] as const satisfies readonly TreeSkill[];

export const V14_ACTIVE_NODES = [
  {
    id: 'rhea.c1',
    role: 'rhea',
    branch: 'c',
    depth: 1,
    name: '游身还击',
    type: 'active',
    skillId: 'wayfarer_riposte',
    minLevel: 10,
    pointCost: 1,
    requires: ['rhea.root'],
  },
  {
    id: 'rhea.a3',
    role: 'rhea',
    branch: 'a',
    depth: 3,
    name: '摧阵突进',
    type: 'active',
    skillId: 'breach_lunge',
    minLevel: 25,
    pointCost: 2,
    requires: ['rhea.a2'],
  },
  {
    id: 'rhea.b3',
    role: 'rhea',
    branch: 'b',
    depth: 3,
    name: '同袍壁垒',
    type: 'active',
    skillId: 'comrades_bastion',
    minLevel: 25,
    pointCost: 2,
    requires: ['rhea.b2'],
  },
  {
    id: 'rhea.c3',
    role: 'rhea',
    branch: 'c',
    depth: 3,
    name: '百折归刃',
    type: 'active',
    skillId: 'unbending_return',
    minLevel: 30,
    pointCost: 2,
    requires: ['rhea.c2'],
  },
  {
    id: 'finn.c1',
    role: 'finn',
    branch: 'c',
    depth: 1,
    name: '毒羽箭',
    type: 'active',
    skillId: 'toxin_fletching',
    minLevel: 10,
    pointCost: 1,
    requires: ['finn.root'],
  },
  {
    id: 'finn.a3',
    role: 'finn',
    branch: 'a',
    depth: 3,
    name: '林幕掩护',
    type: 'active',
    skillId: 'forest_screen',
    minLevel: 25,
    pointCost: 2,
    requires: ['finn.a2'],
  },
  {
    id: 'finn.b3',
    role: 'finn',
    branch: 'b',
    depth: 3,
    name: '穿云狙击',
    type: 'active',
    skillId: 'cloudsplit_aim',
    minLevel: 25,
    pointCost: 2,
    requires: ['finn.b2'],
  },
  {
    id: 'finn.c3',
    role: 'finn',
    branch: 'c',
    depth: 3,
    name: '棘风连射',
    type: 'active',
    skillId: 'thornwind_volley',
    minLevel: 30,
    pointCost: 2,
    requires: ['finn.c2'],
  },
  {
    id: 'luna.c1',
    role: 'luna',
    branch: 'c',
    depth: 1,
    name: '告解之光',
    type: 'active',
    skillId: 'penitent_light',
    minLevel: 10,
    pointCost: 1,
    requires: ['luna.root'],
  },
  {
    id: 'luna.a3',
    role: 'luna',
    branch: 'a',
    depth: 3,
    name: '行世恩光',
    type: 'active',
    skillId: 'mercy_procession',
    minLevel: 25,
    pointCost: 2,
    requires: ['luna.a2'],
  },
  {
    id: 'luna.b3',
    role: 'luna',
    branch: 'b',
    depth: 3,
    name: '银誓圣所',
    type: 'active',
    skillId: 'silver_sanctuary',
    minLevel: 25,
    pointCost: 2,
    requires: ['luna.b2'],
  },
  {
    id: 'luna.c3',
    role: 'luna',
    branch: 'c',
    depth: 3,
    name: '凡人裁决',
    type: 'active',
    skillId: 'mortal_verdict',
    minLevel: 30,
    pointCost: 2,
    requires: ['luna.c2'],
  },
  {
    id: 'kael.c1',
    role: 'kael',
    branch: 'c',
    depth: 1,
    name: '以太汲取',
    type: 'active',
    skillId: 'aether_siphon',
    minLevel: 10,
    pointCost: 1,
    requires: ['kael.root'],
  },
  {
    id: 'kael.a3',
    role: 'kael',
    branch: 'a',
    depth: 3,
    name: '折光封禁',
    type: 'active',
    skillId: 'prism_interdict',
    minLevel: 25,
    pointCost: 2,
    requires: ['kael.a2'],
  },
  {
    id: 'kael.b3',
    role: 'kael',
    branch: 'b',
    depth: 3,
    name: '星群陨落',
    type: 'active',
    skillId: 'falling_constellation',
    minLevel: 25,
    pointCost: 2,
    requires: ['kael.b2'],
  },
  {
    id: 'kael.c3',
    role: 'kael',
    branch: 'c',
    depth: 3,
    name: '奥术解构',
    type: 'active',
    skillId: 'arcane_unraveling',
    minLevel: 30,
    pointCost: 2,
    requires: ['kael.c2'],
  },
  {
    id: 'orin.c1',
    role: 'orin',
    branch: 'c',
    depth: 1,
    name: '誓约重击',
    type: 'active',
    skillId: 'oath_hammer',
    minLevel: 10,
    pointCost: 1,
    requires: ['orin.root'],
  },
  {
    id: 'orin.a3',
    role: 'orin',
    branch: 'a',
    depth: 3,
    name: '聚阵战旗',
    type: 'active',
    skillId: 'rallying_standard',
    minLevel: 25,
    pointCost: 2,
    requires: ['orin.a2'],
  },
  {
    id: 'orin.b3',
    role: 'orin',
    branch: 'b',
    depth: 3,
    name: '铁壁守望',
    type: 'active',
    skillId: 'iron_vigil',
    minLevel: 25,
    pointCost: 2,
    requires: ['orin.b2'],
  },
  {
    id: 'orin.c3',
    role: 'orin',
    branch: 'c',
    depth: 3,
    name: '破晓裁断',
    type: 'active',
    skillId: 'dawn_sentence',
    minLevel: 30,
    pointCost: 2,
    requires: ['orin.c2'],
  },
  {
    id: 'ash.c1',
    role: 'ash',
    branch: 'c',
    depth: 1,
    name: '毒鳞箭',
    type: 'active',
    skillId: 'venomscale_bolt',
    minLevel: 10,
    pointCost: 1,
    requires: ['ash.root'],
  },
  {
    id: 'ash.a3',
    role: 'ash',
    branch: 'a',
    depth: 3,
    name: '净鳞齐射',
    type: 'active',
    skillId: 'cleansing_barrage',
    minLevel: 25,
    pointCost: 2,
    requires: ['ash.a2'],
  },
  {
    id: 'ash.b3',
    role: 'ash',
    branch: 'b',
    depth: 3,
    name: '绝峰贯矢',
    type: 'active',
    skillId: 'highpeak_lance',
    minLevel: 25,
    pointCost: 2,
    requires: ['ash.b2'],
  },
  {
    id: 'ash.c3',
    role: 'ash',
    branch: 'c',
    depth: 3,
    name: '古血毒牙',
    type: 'active',
    skillId: 'ancient_fang',
    minLevel: 30,
    pointCost: 2,
    requires: ['ash.c2'],
  },
  {
    id: 'nyx.c1',
    role: 'nyx',
    branch: 'c',
    depth: 1,
    name: '舞刃',
    type: 'active',
    skillId: 'dancing_knife',
    minLevel: 10,
    pointCost: 1,
    requires: ['nyx.root'],
  },
  {
    id: 'nyx.a3',
    role: 'nyx',
    branch: 'a',
    depth: 3,
    name: '蚀骨切口',
    type: 'active',
    skillId: 'septic_cut',
    minLevel: 25,
    pointCost: 2,
    requires: ['nyx.a2'],
  },
  {
    id: 'nyx.b3',
    role: 'nyx',
    branch: 'b',
    depth: 3,
    name: '影返',
    type: 'active',
    skillId: 'ghost_return',
    minLevel: 25,
    pointCost: 2,
    requires: ['nyx.b2'],
  },
  {
    id: 'nyx.c3',
    role: 'nyx',
    branch: 'c',
    depth: 3,
    name: '终幕剪影',
    type: 'active',
    skillId: 'last_silhouette',
    minLevel: 30,
    pointCost: 2,
    requires: ['nyx.c2'],
  },
  {
    id: 'sylva.c1',
    role: 'sylva',
    branch: 'c',
    depth: 1,
    name: '荒野爪击',
    type: 'active',
    skillId: 'wild_claw',
    minLevel: 10,
    pointCost: 1,
    requires: ['sylva.root'],
  },
  {
    id: 'sylva.a3',
    role: 'sylva',
    branch: 'a',
    depth: 3,
    name: '繁棘牢笼',
    type: 'active',
    skillId: 'briar_prison',
    minLevel: 25,
    pointCost: 2,
    requires: ['sylva.a2'],
  },
  {
    id: 'sylva.b3',
    role: 'sylva',
    branch: 'b',
    depth: 3,
    name: '四时复苏',
    type: 'active',
    skillId: 'four_seasons',
    minLevel: 25,
    pointCost: 2,
    requires: ['sylva.b2'],
  },
  {
    id: 'sylva.c3',
    role: 'sylva',
    branch: 'c',
    depth: 3,
    name: '古木守卫',
    type: 'active',
    skillId: 'ancient_sentinel',
    minLevel: 30,
    pointCost: 2,
    requires: ['sylva.c2'],
  },
  {
    id: 'vera.c1',
    role: 'vera',
    branch: 'c',
    depth: 1,
    name: '闪爆试剂',
    type: 'active',
    skillId: 'flash_reagent',
    minLevel: 10,
    pointCost: 1,
    requires: ['vera.root'],
  },
  {
    id: 'vera.a3',
    role: 'vera',
    branch: 'a',
    depth: 3,
    name: '急救药云',
    type: 'active',
    skillId: 'triage_mist',
    minLevel: 25,
    pointCost: 2,
    requires: ['vera.a2'],
  },
  {
    id: 'vera.b3',
    role: 'vera',
    branch: 'b',
    depth: 3,
    name: '白焰裂瓶',
    type: 'active',
    skillId: 'whitefire_flask',
    minLevel: 25,
    pointCost: 2,
    requires: ['vera.b2'],
  },
  {
    id: 'vera.c3',
    role: 'vera',
    branch: 'c',
    depth: 3,
    name: '解构爆剂',
    type: 'active',
    skillId: 'dissolving_charge',
    minLevel: 30,
    pointCost: 2,
    requires: ['vera.c2'],
  },
] as const satisfies readonly ExtensionNode[];

export const V14_PASSIVE_NODES = [
  {
    id: 'rhea.a4',
    role: 'rhea',
    branch: 'a',
    depth: 4,
    name: '剑锋洞见',
    type: 'passive',
    modifiers: {
      attack: 0.12,
      crit: 0.05,
    },
    minLevel: 35,
    pointCost: 3,
    requires: ['rhea.a3'],
  },
  {
    id: 'rhea.b4',
    role: 'rhea',
    branch: 'b',
    depth: 4,
    name: '护誓传承',
    type: 'passive',
    modifiers: {
      hp: 0.12,
      defense: 0.18,
    },
    minLevel: 35,
    pointCost: 3,
    requires: ['rhea.b3'],
  },
  {
    id: 'rhea.c2',
    role: 'rhea',
    branch: 'c',
    depth: 2,
    name: '游斗熟稔',
    type: 'passive',
    modifiers: {
      attack: 0.06,
      dodge: 0.04,
    },
    minLevel: 20,
    pointCost: 2,
    requires: ['rhea.c1'],
  },
  {
    id: 'rhea.c4',
    role: 'rhea',
    branch: 'c',
    depth: 4,
    name: '无畏归人',
    type: 'passive',
    modifiers: {
      dodge: 0.06,
      critDamage: 0.25,
    },
    minLevel: 40,
    pointCost: 3,
    requires: ['rhea.c3'],
  },
  {
    id: 'finn.a4',
    role: 'finn',
    branch: 'a',
    depth: 4,
    name: '林幕守望',
    type: 'passive',
    modifiers: {
      hp: 0.08,
      defense: 0.12,
      dodge: 0.04,
    },
    minLevel: 35,
    pointCost: 3,
    requires: ['finn.a3'],
  },
  {
    id: 'finn.b4',
    role: 'finn',
    branch: 'b',
    depth: 4,
    name: '长空鹰眼',
    type: 'passive',
    modifiers: {
      crit: 0.1,
      critDamage: 0.3,
    },
    minLevel: 35,
    pointCost: 3,
    requires: ['finn.b3'],
  },
  {
    id: 'finn.c2',
    role: 'finn',
    branch: 'c',
    depth: 2,
    name: '毒羽调律',
    type: 'passive',
    modifiers: {
      attack: 0.08,
      crit: 0.04,
    },
    minLevel: 20,
    pointCost: 2,
    requires: ['finn.c1'],
  },
  {
    id: 'finn.c4',
    role: 'finn',
    branch: 'c',
    depth: 4,
    name: '荒踪绝猎',
    type: 'passive',
    modifiers: {
      attack: 0.12,
      dodge: 0.05,
    },
    minLevel: 40,
    pointCost: 3,
    requires: ['finn.c3'],
  },
  {
    id: 'luna.a4',
    role: 'luna',
    branch: 'a',
    depth: 4,
    name: '长夜慈悲',
    type: 'passive',
    modifiers: {
      healing: 0.25,
      hp: 0.08,
    },
    minLevel: 35,
    pointCost: 3,
    requires: ['luna.a3'],
  },
  {
    id: 'luna.b4',
    role: 'luna',
    branch: 'b',
    depth: 4,
    name: '不灭圣所',
    type: 'passive',
    modifiers: {
      shield: 0.3,
      hp: 0.1,
    },
    minLevel: 35,
    pointCost: 3,
    requires: ['luna.b3'],
  },
  {
    id: 'luna.c2',
    role: 'luna',
    branch: 'c',
    depth: 2,
    name: '戒律修持',
    type: 'passive',
    modifiers: {
      attack: 0.08,
      hp: 0.06,
    },
    minLevel: 20,
    pointCost: 2,
    requires: ['luna.c1'],
  },
  {
    id: 'luna.c4',
    role: 'luna',
    branch: 'c',
    depth: 4,
    name: '凡世裁量',
    type: 'passive',
    modifiers: {
      attack: 0.18,
      crit: 0.06,
    },
    minLevel: 40,
    pointCost: 3,
    requires: ['luna.c3'],
  },
  {
    id: 'kael.a4',
    role: 'kael',
    branch: 'a',
    depth: 4,
    name: '棱光永续',
    type: 'passive',
    modifiers: {
      shield: 0.25,
      defense: 0.1,
    },
    minLevel: 35,
    pointCost: 3,
    requires: ['kael.a3'],
  },
  {
    id: 'kael.b4',
    role: 'kael',
    branch: 'b',
    depth: 4,
    name: '坠星学说',
    type: 'passive',
    modifiers: {
      attack: 0.18,
      critDamage: 0.25,
    },
    minLevel: 35,
    pointCost: 3,
    requires: ['kael.b3'],
  },
  {
    id: 'kael.c2',
    role: 'kael',
    branch: 'c',
    depth: 2,
    name: '奥术节律',
    type: 'passive',
    modifiers: {
      cooldown: 0.25,
      attack: 0.04,
    },
    minLevel: 20,
    pointCost: 2,
    requires: ['kael.c1'],
  },
  {
    id: 'kael.c4',
    role: 'kael',
    branch: 'c',
    depth: 4,
    name: '以太明悟',
    type: 'passive',
    modifiers: {
      attack: 0.1,
      shield: 0.15,
    },
    minLevel: 40,
    pointCost: 3,
    requires: ['kael.c3'],
  },
  {
    id: 'orin.a4',
    role: 'orin',
    branch: 'a',
    depth: 4,
    name: '不散军魂',
    type: 'passive',
    modifiers: {
      shield: 0.15,
      hp: 0.08,
      defense: 0.08,
    },
    minLevel: 35,
    pointCost: 3,
    requires: ['orin.a3'],
  },
  {
    id: 'orin.b4',
    role: 'orin',
    branch: 'b',
    depth: 4,
    name: '城墙之心',
    type: 'passive',
    modifiers: {
      hp: 0.15,
      defense: 0.2,
    },
    minLevel: 35,
    pointCost: 3,
    requires: ['orin.b3'],
  },
  {
    id: 'orin.c2',
    role: 'orin',
    branch: 'c',
    depth: 2,
    name: '裁断戒律',
    type: 'passive',
    modifiers: {
      attack: 0.08,
      defense: 0.08,
    },
    minLevel: 20,
    pointCost: 2,
    requires: ['orin.c1'],
  },
  {
    id: 'orin.c4',
    role: 'orin',
    branch: 'c',
    depth: 4,
    name: '誓火裁决',
    type: 'passive',
    modifiers: {
      attack: 0.16,
      crit: 0.05,
    },
    minLevel: 40,
    pointCost: 3,
    requires: ['orin.c3'],
  },
  {
    id: 'ash.a4',
    role: 'ash',
    branch: 'a',
    depth: 4,
    name: '净鳞誓守',
    type: 'passive',
    modifiers: {
      hp: 0.12,
      defense: 0.1,
    },
    minLevel: 35,
    pointCost: 3,
    requires: ['ash.a3'],
  },
  {
    id: 'ash.b4',
    role: 'ash',
    branch: 'b',
    depth: 4,
    name: '绝峰猎魄',
    type: 'passive',
    modifiers: {
      crit: 0.08,
      critDamage: 0.3,
    },
    minLevel: 35,
    pointCost: 3,
    requires: ['ash.b3'],
  },
  {
    id: 'ash.c2',
    role: 'ash',
    branch: 'c',
    depth: 2,
    name: '古血辨毒',
    type: 'passive',
    modifiers: {
      attack: 0.08,
      hp: 0.08,
    },
    minLevel: 20,
    pointCost: 2,
    requires: ['ash.c1'],
  },
  {
    id: 'ash.c4',
    role: 'ash',
    branch: 'c',
    depth: 4,
    name: '万毒猎踪',
    type: 'passive',
    modifiers: {
      attack: 0.15,
      dodge: 0.05,
    },
    minLevel: 40,
    pointCost: 3,
    requires: ['ash.c3'],
  },
  {
    id: 'nyx.a4',
    role: 'nyx',
    branch: 'a',
    depth: 4,
    name: '蚀骨秘术',
    type: 'passive',
    modifiers: {
      attack: 0.18,
      crit: 0.05,
    },
    minLevel: 35,
    pointCost: 3,
    requires: ['nyx.a3'],
  },
  {
    id: 'nyx.b4',
    role: 'nyx',
    branch: 'b',
    depth: 4,
    name: '夜幕行者',
    type: 'passive',
    modifiers: {
      dodge: 0.1,
      hp: 0.08,
    },
    minLevel: 35,
    pointCost: 3,
    requires: ['nyx.b3'],
  },
  {
    id: 'nyx.c2',
    role: 'nyx',
    branch: 'c',
    depth: 2,
    name: '终幕舞步',
    type: 'passive',
    modifiers: {
      crit: 0.06,
      attack: 0.06,
    },
    minLevel: 20,
    pointCost: 2,
    requires: ['nyx.c1'],
  },
  {
    id: 'nyx.c4',
    role: 'nyx',
    branch: 'c',
    depth: 4,
    name: '寂灭剪影',
    type: 'passive',
    modifiers: {
      crit: 0.1,
      critDamage: 0.35,
    },
    minLevel: 40,
    pointCost: 3,
    requires: ['nyx.c3'],
  },
  {
    id: 'sylva.a4',
    role: 'sylva',
    branch: 'a',
    depth: 4,
    name: '千棘传承',
    type: 'passive',
    modifiers: {
      attack: 0.15,
      crit: 0.06,
    },
    minLevel: 35,
    pointCost: 3,
    requires: ['sylva.a3'],
  },
  {
    id: 'sylva.b4',
    role: 'sylva',
    branch: 'b',
    depth: 4,
    name: '长生林语',
    type: 'passive',
    modifiers: {
      healing: 0.2,
      shield: 0.2,
    },
    minLevel: 35,
    pointCost: 3,
    requires: ['sylva.b3'],
  },
  {
    id: 'sylva.c2',
    role: 'sylva',
    branch: 'c',
    depth: 2,
    name: '野性血脉',
    type: 'passive',
    modifiers: {
      hp: 0.1,
      attack: 0.05,
    },
    minLevel: 20,
    pointCost: 2,
    requires: ['sylva.c1'],
  },
  {
    id: 'sylva.c4',
    role: 'sylva',
    branch: 'c',
    depth: 4,
    name: '古林巨灵',
    type: 'passive',
    modifiers: {
      hp: 0.15,
      defense: 0.12,
    },
    minLevel: 40,
    pointCost: 3,
    requires: ['sylva.c3'],
  },
  {
    id: 'vera.a4',
    role: 'vera',
    branch: 'a',
    depth: 4,
    name: '救护真解',
    type: 'passive',
    modifiers: {
      healing: 0.25,
      hp: 0.08,
    },
    minLevel: 35,
    pointCost: 3,
    requires: ['vera.a3'],
  },
  {
    id: 'vera.b4',
    role: 'vera',
    branch: 'b',
    depth: 4,
    name: '白焰配方',
    type: 'passive',
    modifiers: {
      attack: 0.18,
      critDamage: 0.2,
    },
    minLevel: 35,
    pointCost: 3,
    requires: ['vera.b3'],
  },
  {
    id: 'vera.c2',
    role: 'vera',
    branch: 'c',
    depth: 2,
    name: '战剂速配',
    type: 'passive',
    modifiers: {
      cooldown: 0.25,
      attack: 0.03,
    },
    minLevel: 20,
    pointCost: 2,
    requires: ['vera.c1'],
  },
  {
    id: 'vera.c4',
    role: 'vera',
    branch: 'c',
    depth: 4,
    name: '终极调剂',
    type: 'passive',
    modifiers: {
      hp: 0.12,
      defense: 0.15,
    },
    minLevel: 40,
    pointCost: 3,
    requires: ['vera.c3'],
  },
] as const satisfies readonly ExtensionNode[];

export const V14_THIRD_BRANCH_NAMES = {
  rhea: '游斗',
  finn: '毒羽',
  luna: '戒律',
  kael: '奥术',
  orin: '裁断',
  ash: '古毒',
  nyx: '终幕',
  sylva: '野性',
  vera: '战剂',
} as const satisfies Record<TreeRole, string>;
