import {
  V14_ACTIVE_SKILLS,
  V14_ACTIVE_NODES,
  V14_PASSIVE_NODES,
} from './skill-extension.ts';
export { V14_THIRD_BRANCH_NAMES } from './skill-extension.ts';
/** Profession and skill-tree data for the personal-turn engine. No executable game logic. */
export type TreeRole =
  | 'rhea'
  | 'finn'
  | 'luna'
  | 'kael'
  | 'orin'
  | 'ash'
  | 'nyx'
  | 'sylva'
  | 'vera';
export type SkillModifier = {
  hp?: number;
  attack?: number;
  defense?: number;
  crit?: number;
  dodge?: number;
  critDamage?: number;
  healing?: number;
  shield?: number;
  cooldown?: number;
};
export type TreeSkill = {
  id: string;
  role: TreeRole;
  name: string;
  description: string;
  target: 'enemy' | 'ally' | 'self' | 'party';
  energy: number;
  cooldown: number;
  damage: number;
  legacyId?: boolean;
  supply?: 1;
  projectile?: boolean;
  interrupt?: boolean;
  shatter?: boolean;
  cleanseBurn?: boolean;
  preventBurn?: boolean;
  wardHits?: number;
  markHits?: number;
  incomingMultiplier?: number;
  energyRefund?: number;
  lateBossMultiplier?: number;
  heal?: 'mortal_light' | 'steadfast_prayer';
  healing?: { actorHp: number; actorAttack: number; targetHp: number };
  shield?: { actorHp: number; actorAttack: number; rounds: number };
  dot?: { kind: 'poison' | 'fire'; actorAttack: number; rounds: number };
  regen?: { actorHp: number; actorAttack: number; rounds: number };
  taunt?: number;
  evasion?: number;
  critBonus?: number;
  pierceBonus?: number;
  detonateFire?: boolean;
};
export type SkillTreeNode = {
  id: string;
  role: TreeRole;
  branch: 'root' | 'a' | 'b' | 'c';
  depth: 0 | 1 | 2 | 3 | 4;
  name: string;
  type: 'active' | 'passive';
  skillId?: string;
  modifiers?: SkillModifier;
  pointCost: 0 | 1 | 2 | 3;
  minLevel: number;
  requires: readonly string[];
};
export type TreeRoleDefinition = {
  id: TreeRole;
  name: string;
  root: string;
  a: string;
  b: string;
  branches: readonly [string, string];
  hp: number;
  attack: number;
  defense: number;
  crit: number;
  dodge: number;
  ranged: number;
  townRank: number;
};

export const TREE_RULES = {
  pointLevels: [5, 10, 15, 20, 25, 30, 35, 40],
  rootAlwaysAvailable: true,
  branchLoadoutSlots: 2,
  baseCritDamage: 1.5,
  critCap: 0.6,
  dodgeCap: 0.4,
  pierceCap: 0.75,
  cooldownReductionCap: 0.3,
  shieldCapOfTargetMaxHp: 0.6,
  wardMultiplier: 0.55,
  markMultiplier: 1.2,
  maxMarkHits: 2,
  maxWardHits: 2,
  guardDurationEnemyPhases: 1,
  statusKinds: ['dot', 'regen', 'taunt'],
  dotStacks: false,
  regenStacks: false,
  shieldStacks: false,
  reset: {
    location: 'town',
    goldCost: 0,
    refund: 'all_spent_points',
    lock: 'only_away_members',
    clearLegacySkill: false,
  },
  legacy: {
    preserveIds: [
      'home_oath',
      'shield_breaker',
      'hunter_mark',
      'covering_shot',
      'mortal_light',
      'steadfast_prayer',
      'star_shatter',
      'star_ward',
      'unfallen_shield',
      'battle_standard',
      'sky_arrow',
      'scale_cleanse',
    ],
    missingActiveSkill: 'role_root',
    nonRootActiveSkill: 'copy_to_legacySkill',
    legacyNodeCostCredit: 0,
  },
} as const;

export const TREE_ROLES = [
  {
    id: 'rhea',
    name: '流浪剑士',
    root: 'home_oath',
    a: 'shield_breaker',
    b: 'challengers_oath',
    branches: ['破阵', '守护'],
    hp: 120,
    attack: 18,
    defense: 4,
    crit: 0.05,
    dodge: 0.05,
    ranged: 0,
    townRank: 0,
  },
  {
    id: 'finn',
    name: '半精灵游侠',
    root: 'hunter_mark',
    a: 'covering_shot',
    b: 'piercing_volley',
    branches: ['掩护', '狙击'],
    hp: 88,
    attack: 23,
    defense: 2,
    crit: 0.08,
    dodge: 0.08,
    ranged: 1,
    townRank: 0,
  },
  {
    id: 'luna',
    name: '失誓修女',
    root: 'mortal_light',
    a: 'steadfast_prayer',
    b: 'sanctuary',
    branches: ['祷告', '庇护'],
    hp: 110,
    attack: 17,
    defense: 3,
    crit: 0.05,
    dodge: 0.05,
    ranged: 0,
    townRank: 0,
  },
  {
    id: 'kael',
    name: '逐星法师',
    root: 'star_shatter',
    a: 'star_ward',
    b: 'meteor',
    branches: ['屏障', '星火'],
    hp: 85,
    attack: 29,
    defense: 1,
    crit: 0.05,
    dodge: 0.05,
    ranged: 0.6,
    townRank: 0,
  },
  {
    id: 'orin',
    name: '灰誓骑士',
    root: 'unfallen_shield',
    a: 'battle_standard',
    b: 'guardian_sanctuary',
    branches: ['军阵', '壁垒'],
    hp: 160,
    attack: 22,
    defense: 7,
    crit: 0.05,
    dodge: 0.03,
    ranged: 0,
    townRank: 1,
  },
  {
    id: 'ash',
    name: '龙裔猎人',
    root: 'sky_arrow',
    a: 'scale_cleanse',
    b: 'cinder_lance',
    branches: ['净鳞', '焚猎'],
    hp: 120,
    attack: 34,
    defense: 4,
    crit: 0.08,
    dodge: 0.05,
    ranged: 1,
    townRank: 3,
  },
  {
    id: 'nyx',
    name: '夜行刺客',
    root: 'shadow_stab',
    a: 'venom_edge',
    b: 'smoke_step',
    branches: ['毒刃', '影步'],
    hp: 82,
    attack: 26,
    defense: 1,
    crit: 0.12,
    dodge: 0.12,
    ranged: 0,
    townRank: 1,
  },
  {
    id: 'sylva',
    name: '荒林德鲁伊',
    root: 'verdant_touch',
    a: 'bramble_wrap',
    b: 'barkskin',
    branches: ['荆棘', '生息'],
    hp: 115,
    attack: 20,
    defense: 3,
    crit: 0.05,
    dodge: 0.06,
    ranged: 0.5,
    townRank: 1,
  },
  {
    id: 'vera',
    name: '行旅炼金师',
    root: 'acid_flask',
    a: 'mending_mist',
    b: 'volatile_bomb',
    branches: ['药理', '烈剂'],
    hp: 100,
    attack: 22,
    defense: 2,
    crit: 0.06,
    dodge: 0.05,
    ranged: 0.8,
    townRank: 2,
  },
] as const satisfies readonly TreeRoleDefinition[];

export const TREE_SKILLS = [
  ...V14_ACTIVE_SKILLS,
  {
    id: 'home_oath',
    role: 'rhea',
    name: '守家之誓',
    energy: 2,
    cooldown: 4,
    damage: 0.8,
    wardHits: 2,
    description:
      '造成80%本人攻击伤害，并使指定友方接下来两次受击减伤45%；护佑最多持续两次敌方阶段。',
    target: 'ally',
    legacyId: true,
  },
  {
    id: 'shield_breaker',
    role: 'rhea',
    name: '破阵盾击',
    energy: 2,
    cooldown: 3,
    damage: 1.05,
    shatter: true,
    description:
      '击碎当前护盾并造成 105% 技能伤害；不打断补给或咏唱，不提供护佑。',
    target: 'enemy',
    legacyId: true,
  },
  {
    id: 'hunter_mark',
    role: 'finn',
    name: '猎人印记',
    energy: 2,
    cooldown: 3,
    damage: 1.2,
    projectile: true,
    markHits: 2,
    description:
      '造成 120% 技能伤害；随后两次有伤害的行动增伤 20%。施技者可命中飞行敌人。',
    target: 'enemy',
    legacyId: true,
  },
  {
    id: 'covering_shot',
    role: 'finn',
    name: '掩护射击',
    energy: 1,
    cooldown: 2,
    damage: 0.8,
    projectile: true,
    incomingMultiplier: 0.65,
    description: '造成80%本人投射伤害，指定友方在接下来的敌方阶段承伤降低35%。',
    target: 'ally',
    legacyId: true,
  },
  {
    id: 'mortal_light',
    role: 'luna',
    name: '人间微光',
    energy: 3,
    cooldown: 4,
    damage: 0,
    heal: 'mortal_light',
    supply: 1,
    cleanseBurn: true,
    description: '消耗1药囊，恢复指定友方生命并净化其灼烧；受到禁疗限制。',
    target: 'ally',
    healing: {
      actorHp: 0.6,
      actorAttack: 1,
      targetHp: 0.2,
    },
    legacyId: true,
  },
  {
    id: 'steadfast_prayer',
    role: 'luna',
    name: '不息祷言',
    energy: 4,
    cooldown: 4,
    damage: 0,
    heal: 'steadfast_prayer',
    description:
      '消耗4士气、不耗药囊，较弱治疗指定友方；不净化灼烧，受到禁疗限制。',
    target: 'ally',
    healing: {
      actorHp: 0.25,
      actorAttack: 0.5,
      targetHp: 0.08,
    },
    legacyId: true,
  },
  {
    id: 'star_shatter',
    role: 'kael',
    name: '碎星术',
    energy: 3,
    cooldown: 4,
    damage: 1.8,
    projectile: true,
    interrupt: true,
    shatter: true,
    description: '造成 180% 技能伤害，击碎护盾并打断本次补给或咏唱。',
    target: 'enemy',
    legacyId: true,
  },
  {
    id: 'star_ward',
    role: 'kael',
    name: '星界屏障',
    energy: 2,
    cooldown: 3,
    damage: 0.6,
    projectile: true,
    wardHits: 2,
    description:
      '造成60%本人投射伤害，给予指定友方两次45%减伤护佑；不破盾、不打断。',
    target: 'ally',
    legacyId: true,
  },
  {
    id: 'unfallen_shield',
    role: 'orin',
    name: '不落之盾',
    energy: 2,
    cooldown: 3,
    damage: 0.9,
    incomingMultiplier: 0.15,
    energyRefund: 1,
    preventBurn: true,
    description:
      '造成90%本人攻击伤害，自己在下次敌方阶段承伤降低85%，嘲讽下次单体攻击；耗2士气返1，防止新灼烧。',
    target: 'self',
    taunt: 1,
    legacyId: true,
  },
  {
    id: 'battle_standard',
    role: 'orin',
    name: '军阵号令',
    energy: 2,
    cooldown: 4,
    damage: 0.6,
    markHits: 2,
    wardHits: 1,
    description:
      '造成60%本人攻击伤害，指定友方下次受击减伤45%；标记敌人，随后两次直接伤害提高20%。',
    target: 'ally',
    legacyId: true,
  },
  {
    id: 'sky_arrow',
    role: 'ash',
    name: '断天之矢',
    energy: 3,
    cooldown: 3,
    damage: 1.7,
    projectile: true,
    shatter: true,
    lateBossMultiplier: 1.1,
    description:
      '造成 170% 技能伤害，击碎护盾；施技者可命中飞行敌人，对古龙与神明再增伤 10%。',
    target: 'enemy',
    legacyId: true,
  },
  {
    id: 'scale_cleanse',
    role: 'ash',
    name: '焚鳞净身',
    energy: 2,
    cooldown: 3,
    damage: 1,
    projectile: true,
    cleanseBurn: true,
    preventBurn: true,
    incomingMultiplier: 0.7,
    description:
      '造成100%本人投射伤害，清除自身灼烧，下次敌方阶段承伤降低30%并防止新灼烧；不破盾。',
    target: 'self',
    legacyId: true,
  },
  {
    id: 'challengers_oath',
    role: 'rhea',
    name: '迎敌之誓',
    description:
      '造成80%本人攻击伤害，获得自身最大生命18%的护盾，并嘲讽下次敌方单体攻击。',
    target: 'self',
    energy: 2,
    cooldown: 3,
    damage: 0.8,
    shield: {
      actorHp: 0.18,
      actorAttack: 0,
      rounds: 1,
    },
    taunt: 1,
  },
  {
    id: 'piercing_volley',
    role: 'finn',
    name: '贯甲连射',
    description: '造成145%本人投射伤害，本次攻击额外穿甲30%；不清除魔法护盾。',
    target: 'enemy',
    energy: 3,
    cooldown: 3,
    damage: 1.45,
    projectile: true,
    pierceBonus: 0.3,
  },
  {
    id: 'sanctuary',
    role: 'luna',
    name: '安息结界',
    description:
      '为指定友方提供基于本人生命35%与攻击100%的护盾，净化灼烧；不恢复生命，禁疗期间仍可使用。',
    target: 'ally',
    energy: 3,
    cooldown: 4,
    damage: 0,
    shield: {
      actorHp: 0.35,
      actorAttack: 1,
      rounds: 2,
    },
    cleanseBurn: true,
  },
  {
    id: 'meteor',
    role: 'kael',
    name: '星陨咒',
    description:
      '造成240%本人投射伤害，本次暴击率额外10%；引爆队伍全部燃烧，结算剩余伤害的80%，最多120%本人攻击；不破盾，不打断。引爆消耗余火，不暴击。',
    target: 'enemy',
    energy: 4,
    cooldown: 4,
    damage: 2.4,
    detonateFire: true,
    projectile: true,
    critBonus: 0.1,
  },
  {
    id: 'guardian_sanctuary',
    role: 'orin',
    name: '众盾庇护',
    description:
      '给每位存活队友提供本人最大生命12%与攻击40%的护盾；同一目标护盾只取较高值，不叠加。',
    target: 'party',
    energy: 3,
    cooldown: 4,
    damage: 0,
    shield: {
      actorHp: 0.12,
      actorAttack: 0.4,
      rounds: 2,
    },
  },
  {
    id: 'cinder_lance',
    role: 'ash',
    name: '余烬投枪',
    description:
      '造成120%本人投射伤害，附加两轮余烬伤害，每轮为本人施放时攻击的35%；持续伤害不暴击。',
    target: 'enemy',
    energy: 3,
    cooldown: 3,
    damage: 1.2,
    projectile: true,
    dot: {
      kind: 'fire',
      actorAttack: 0.35,
      rounds: 2,
    },
  },
  {
    id: 'shadow_stab',
    role: 'nyx',
    name: '潜影刺',
    description: '造成125%本人攻击伤害，本次暴击率额外15%。',
    target: 'enemy',
    energy: 2,
    cooldown: 2,
    damage: 1.25,
    critBonus: 0.15,
  },
  {
    id: 'venom_edge',
    role: 'nyx',
    name: '淬毒刃',
    description:
      '造成70%本人攻击伤害，附加两轮毒伤，每轮为本人施放时攻击的40%；毒伤不暴击，不叠层。',
    target: 'enemy',
    energy: 2,
    cooldown: 3,
    damage: 0.7,
    dot: {
      kind: 'poison',
      actorAttack: 0.4,
      rounds: 2,
    },
  },
  {
    id: 'smoke_step',
    role: 'nyx',
    name: '烟幕步',
    description:
      '造成50%本人攻击伤害，自己在下次敌方阶段闪避率增加25%；无法保证闪避。',
    target: 'self',
    energy: 1,
    cooldown: 3,
    damage: 0.5,
    evasion: 0.25,
  },
  {
    id: 'verdant_touch',
    role: 'sylva',
    name: '青枝抚愈',
    description:
      '治疗指定友方，并给予两次再生；治疗与再生都受禁疗限制，续期不叠加。',
    target: 'ally',
    energy: 2,
    cooldown: 3,
    damage: 0,
    healing: {
      actorHp: 0.08,
      actorAttack: 1.1,
      targetHp: 0,
    },
    regen: {
      actorHp: 0.04,
      actorAttack: 0.35,
      rounds: 2,
    },
  },
  {
    id: 'bramble_wrap',
    role: 'sylva',
    name: '荆棘缠身',
    description:
      '造成80%本人投射伤害，附加两轮荆毒，每轮为本人施放时攻击的45%；不阻止敌方行动。',
    target: 'enemy',
    energy: 2,
    cooldown: 3,
    damage: 0.8,
    projectile: true,
    dot: {
      kind: 'poison',
      actorAttack: 0.45,
      rounds: 2,
    },
  },
  {
    id: 'barkskin',
    role: 'sylva',
    name: '树皮护身',
    description:
      '为指定友方提供本人生命25%与攻击50%的护盾，并防止其下次敌方阶段新受灼烧。',
    target: 'ally',
    energy: 2,
    cooldown: 3,
    damage: 0,
    shield: {
      actorHp: 0.25,
      actorAttack: 0.5,
      rounds: 2,
    },
    preventBurn: true,
  },
  {
    id: 'acid_flask',
    role: 'vera',
    name: '蚀甲药瓶',
    description: '造成110%本人投射伤害，本次攻击额外穿甲25%；不清除魔法护盾。',
    target: 'enemy',
    energy: 2,
    cooldown: 2,
    damage: 1.1,
    projectile: true,
    pierceBonus: 0.25,
  },
  {
    id: 'mending_mist',
    role: 'vera',
    name: '复苏药雾',
    description:
      '消耗1药囊，为每位存活队友回复本人攻击65%与目标最大生命5%；不会复活倒下者，受禁疗限制。',
    target: 'party',
    energy: 2,
    cooldown: 3,
    damage: 0,
    supply: 1,
    healing: {
      actorHp: 0,
      actorAttack: 0.65,
      targetHp: 0.05,
    },
  },
  {
    id: 'volatile_bomb',
    role: 'vera',
    name: '烈性燃瓶',
    description:
      '造成130%本人投射伤害，附加两轮燃烧，每轮为本人施放时攻击的50%；不破盾、不打断。',
    target: 'enemy',
    energy: 3,
    cooldown: 4,
    damage: 1.3,
    projectile: true,
    dot: {
      kind: 'fire',
      actorAttack: 0.5,
      rounds: 2,
    },
  },
] as const satisfies readonly TreeSkill[];

export const SKILL_TREE_NODES = [
  ...V14_ACTIVE_NODES,
  ...V14_PASSIVE_NODES,
  {
    id: 'rhea.root',
    role: 'rhea',
    branch: 'root',
    depth: 0,
    name: '守家之誓',
    type: 'active',
    skillId: 'home_oath',
    pointCost: 0,
    minLevel: 1,
    requires: [],
  },
  {
    id: 'rhea.a1',
    role: 'rhea',
    branch: 'a',
    depth: 1,
    name: '破阵盾击',
    type: 'active',
    skillId: 'shield_breaker',
    pointCost: 1,
    minLevel: 5,
    requires: ['rhea.root'],
  },
  {
    id: 'rhea.a2',
    role: 'rhea',
    branch: 'a',
    depth: 2,
    name: '破阵心得',
    type: 'passive',
    modifiers: {
      attack: 0.1,
      crit: 0.05,
    },
    pointCost: 2,
    minLevel: 15,
    requires: ['rhea.a1'],
  },
  {
    id: 'rhea.b1',
    role: 'rhea',
    branch: 'b',
    depth: 1,
    name: '迎敌之誓',
    type: 'active',
    skillId: 'challengers_oath',
    pointCost: 1,
    minLevel: 5,
    requires: ['rhea.root'],
  },
  {
    id: 'rhea.b2',
    role: 'rhea',
    branch: 'b',
    depth: 2,
    name: '守卫体魄',
    type: 'passive',
    modifiers: {
      hp: 0.12,
      defense: 0.15,
    },
    pointCost: 2,
    minLevel: 15,
    requires: ['rhea.b1'],
  },
  {
    id: 'finn.root',
    role: 'finn',
    branch: 'root',
    depth: 0,
    name: '猎人印记',
    type: 'active',
    skillId: 'hunter_mark',
    pointCost: 0,
    minLevel: 1,
    requires: [],
  },
  {
    id: 'finn.a1',
    role: 'finn',
    branch: 'a',
    depth: 1,
    name: '掩护射击',
    type: 'active',
    skillId: 'covering_shot',
    pointCost: 1,
    minLevel: 5,
    requires: ['finn.root'],
  },
  {
    id: 'finn.a2',
    role: 'finn',
    branch: 'a',
    depth: 2,
    name: '林间步法',
    type: 'passive',
    modifiers: {
      dodge: 0.08,
      defense: 0.1,
    },
    pointCost: 2,
    minLevel: 15,
    requires: ['finn.a1'],
  },
  {
    id: 'finn.b1',
    role: 'finn',
    branch: 'b',
    depth: 1,
    name: '贯甲连射',
    type: 'active',
    skillId: 'piercing_volley',
    pointCost: 1,
    minLevel: 5,
    requires: ['finn.root'],
  },
  {
    id: 'finn.b2',
    role: 'finn',
    branch: 'b',
    depth: 2,
    name: '鹰眼专精',
    type: 'passive',
    modifiers: {
      crit: 0.1,
      critDamage: 0.25,
    },
    pointCost: 2,
    minLevel: 15,
    requires: ['finn.b1'],
  },
  {
    id: 'luna.root',
    role: 'luna',
    branch: 'root',
    depth: 0,
    name: '人间微光',
    type: 'active',
    skillId: 'mortal_light',
    pointCost: 0,
    minLevel: 1,
    requires: [],
  },
  {
    id: 'luna.a1',
    role: 'luna',
    branch: 'a',
    depth: 1,
    name: '不息祷言',
    type: 'active',
    skillId: 'steadfast_prayer',
    pointCost: 1,
    minLevel: 5,
    requires: ['luna.root'],
  },
  {
    id: 'luna.a2',
    role: 'luna',
    branch: 'a',
    depth: 2,
    name: '长祷',
    type: 'passive',
    modifiers: {
      healing: 0.2,
      cooldown: 0.25,
    },
    pointCost: 2,
    minLevel: 15,
    requires: ['luna.a1'],
  },
  {
    id: 'luna.b1',
    role: 'luna',
    branch: 'b',
    depth: 1,
    name: '安息结界',
    type: 'active',
    skillId: 'sanctuary',
    pointCost: 1,
    minLevel: 5,
    requires: ['luna.root'],
  },
  {
    id: 'luna.b2',
    role: 'luna',
    branch: 'b',
    depth: 2,
    name: '慈悲壁垒',
    type: 'passive',
    modifiers: {
      shield: 0.25,
      hp: 0.08,
    },
    pointCost: 2,
    minLevel: 15,
    requires: ['luna.b1'],
  },
  {
    id: 'kael.root',
    role: 'kael',
    branch: 'root',
    depth: 0,
    name: '碎星术',
    type: 'active',
    skillId: 'star_shatter',
    pointCost: 0,
    minLevel: 1,
    requires: [],
  },
  {
    id: 'kael.a1',
    role: 'kael',
    branch: 'a',
    depth: 1,
    name: '星界屏障',
    type: 'active',
    skillId: 'star_ward',
    pointCost: 1,
    minLevel: 5,
    requires: ['kael.root'],
  },
  {
    id: 'kael.a2',
    role: 'kael',
    branch: 'a',
    depth: 2,
    name: '稳固结界',
    type: 'passive',
    modifiers: {
      defense: 0.15,
      dodge: 0.05,
    },
    pointCost: 2,
    minLevel: 15,
    requires: ['kael.a1'],
  },
  {
    id: 'kael.b1',
    role: 'kael',
    branch: 'b',
    depth: 1,
    name: '星陨咒',
    type: 'active',
    skillId: 'meteor',
    pointCost: 1,
    minLevel: 5,
    requires: ['kael.root'],
  },
  {
    id: 'kael.b2',
    role: 'kael',
    branch: 'b',
    depth: 2,
    name: '星火共鸣',
    type: 'passive',
    modifiers: {
      attack: 0.12,
      critDamage: 0.2,
    },
    pointCost: 2,
    minLevel: 15,
    requires: ['kael.b1'],
  },
  {
    id: 'orin.root',
    role: 'orin',
    branch: 'root',
    depth: 0,
    name: '不落之盾',
    type: 'active',
    skillId: 'unfallen_shield',
    pointCost: 0,
    minLevel: 1,
    requires: [],
  },
  {
    id: 'orin.a1',
    role: 'orin',
    branch: 'a',
    depth: 1,
    name: '军阵号令',
    type: 'active',
    skillId: 'battle_standard',
    pointCost: 1,
    minLevel: 5,
    requires: ['orin.root'],
  },
  {
    id: 'orin.a2',
    role: 'orin',
    branch: 'a',
    depth: 2,
    name: '军阵纪律',
    type: 'passive',
    modifiers: {
      attack: 0.08,
      defense: 0.12,
    },
    pointCost: 2,
    minLevel: 15,
    requires: ['orin.a1'],
  },
  {
    id: 'orin.b1',
    role: 'orin',
    branch: 'b',
    depth: 1,
    name: '众盾庇护',
    type: 'active',
    skillId: 'guardian_sanctuary',
    pointCost: 1,
    minLevel: 5,
    requires: ['orin.root'],
  },
  {
    id: 'orin.b2',
    role: 'orin',
    branch: 'b',
    depth: 2,
    name: '重盾工艺',
    type: 'passive',
    modifiers: {
      shield: 0.3,
      hp: 0.1,
    },
    pointCost: 2,
    minLevel: 15,
    requires: ['orin.b1'],
  },
  {
    id: 'ash.root',
    role: 'ash',
    branch: 'root',
    depth: 0,
    name: '断天之矢',
    type: 'active',
    skillId: 'sky_arrow',
    pointCost: 0,
    minLevel: 1,
    requires: [],
  },
  {
    id: 'ash.a1',
    role: 'ash',
    branch: 'a',
    depth: 1,
    name: '焚鳞净身',
    type: 'active',
    skillId: 'scale_cleanse',
    pointCost: 1,
    minLevel: 5,
    requires: ['ash.root'],
  },
  {
    id: 'ash.a2',
    role: 'ash',
    branch: 'a',
    depth: 2,
    name: '余烬耐性',
    type: 'passive',
    modifiers: {
      hp: 0.1,
      dodge: 0.05,
    },
    pointCost: 2,
    minLevel: 15,
    requires: ['ash.a1'],
  },
  {
    id: 'ash.b1',
    role: 'ash',
    branch: 'b',
    depth: 1,
    name: '余烬投枪',
    type: 'active',
    skillId: 'cinder_lance',
    pointCost: 1,
    minLevel: 5,
    requires: ['ash.root'],
  },
  {
    id: 'ash.b2',
    role: 'ash',
    branch: 'b',
    depth: 2,
    name: '狩龙眼',
    type: 'passive',
    modifiers: {
      attack: 0.12,
      crit: 0.08,
    },
    pointCost: 2,
    minLevel: 15,
    requires: ['ash.b1'],
  },
  {
    id: 'nyx.root',
    role: 'nyx',
    branch: 'root',
    depth: 0,
    name: '潜影刺',
    type: 'active',
    skillId: 'shadow_stab',
    pointCost: 0,
    minLevel: 1,
    requires: [],
  },
  {
    id: 'nyx.a1',
    role: 'nyx',
    branch: 'a',
    depth: 1,
    name: '淬毒刃',
    type: 'active',
    skillId: 'venom_edge',
    pointCost: 1,
    minLevel: 5,
    requires: ['nyx.root'],
  },
  {
    id: 'nyx.a2',
    role: 'nyx',
    branch: 'a',
    depth: 2,
    name: '毒刃专精',
    type: 'passive',
    modifiers: {
      attack: 0.1,
      crit: 0.08,
    },
    pointCost: 2,
    minLevel: 15,
    requires: ['nyx.a1'],
  },
  {
    id: 'nyx.b1',
    role: 'nyx',
    branch: 'b',
    depth: 1,
    name: '烟幕步',
    type: 'active',
    skillId: 'smoke_step',
    pointCost: 1,
    minLevel: 5,
    requires: ['nyx.root'],
  },
  {
    id: 'nyx.b2',
    role: 'nyx',
    branch: 'b',
    depth: 2,
    name: '无声步',
    type: 'passive',
    modifiers: {
      dodge: 0.1,
      crit: 0.05,
    },
    pointCost: 2,
    minLevel: 15,
    requires: ['nyx.b1'],
  },
  {
    id: 'sylva.root',
    role: 'sylva',
    branch: 'root',
    depth: 0,
    name: '青枝抚愈',
    type: 'active',
    skillId: 'verdant_touch',
    pointCost: 0,
    minLevel: 1,
    requires: [],
  },
  {
    id: 'sylva.a1',
    role: 'sylva',
    branch: 'a',
    depth: 1,
    name: '荆棘缠身',
    type: 'active',
    skillId: 'bramble_wrap',
    pointCost: 1,
    minLevel: 5,
    requires: ['sylva.root'],
  },
  {
    id: 'sylva.a2',
    role: 'sylva',
    branch: 'a',
    depth: 2,
    name: '荆棘学识',
    type: 'passive',
    modifiers: {
      attack: 0.12,
      crit: 0.05,
    },
    pointCost: 2,
    minLevel: 15,
    requires: ['sylva.a1'],
  },
  {
    id: 'sylva.b1',
    role: 'sylva',
    branch: 'b',
    depth: 1,
    name: '树皮护身',
    type: 'active',
    skillId: 'barkskin',
    pointCost: 1,
    minLevel: 5,
    requires: ['sylva.root'],
  },
  {
    id: 'sylva.b2',
    role: 'sylva',
    branch: 'b',
    depth: 2,
    name: '繁茂',
    type: 'passive',
    modifiers: {
      healing: 0.15,
      shield: 0.15,
    },
    pointCost: 2,
    minLevel: 15,
    requires: ['sylva.b1'],
  },
  {
    id: 'vera.root',
    role: 'vera',
    branch: 'root',
    depth: 0,
    name: '蚀甲药瓶',
    type: 'active',
    skillId: 'acid_flask',
    pointCost: 0,
    minLevel: 1,
    requires: [],
  },
  {
    id: 'vera.a1',
    role: 'vera',
    branch: 'a',
    depth: 1,
    name: '复苏药雾',
    type: 'active',
    skillId: 'mending_mist',
    pointCost: 1,
    minLevel: 5,
    requires: ['vera.root'],
  },
  {
    id: 'vera.a2',
    role: 'vera',
    branch: 'a',
    depth: 2,
    name: '药理精修',
    type: 'passive',
    modifiers: {
      healing: 0.2,
      hp: 0.1,
    },
    pointCost: 2,
    minLevel: 15,
    requires: ['vera.a1'],
  },
  {
    id: 'vera.b1',
    role: 'vera',
    branch: 'b',
    depth: 1,
    name: '烈性燃瓶',
    type: 'active',
    skillId: 'volatile_bomb',
    pointCost: 1,
    minLevel: 5,
    requires: ['vera.root'],
  },
  {
    id: 'vera.b2',
    role: 'vera',
    branch: 'b',
    depth: 2,
    name: '精密配比',
    type: 'passive',
    modifiers: {
      attack: 0.1,
      critDamage: 0.25,
    },
    pointCost: 2,
    minLevel: 15,
    requires: ['vera.b1'],
  },
] as const satisfies readonly SkillTreeNode[];
